Repository App-vNext/Polly, pull requests merged in 2018-07, with the labels that each got.

#480 Create pull_request_template
  .github/pull_request_template.md
Labels: documentation

#471 Add wait and retry forever overloads
  README.md
  src/Polly.Shared/Polly.Shared.projitems
  src/Polly.Shared/Retry/RetryStateRetryForeverWithCount.cs
  src/Polly.Shared/Retry/RetryStateRetryForeverWithCountAsync.cs
  src/Polly.Shared/Retry/RetryStateWaitAndRetryForeverWithCount.cs
  src/Polly.Shared/Retry/RetryStateWaitAndRetryForeverWithCountAsync.cs
  src/Polly.Shared/Retry/RetrySyntax.cs
  src/Polly.Shared/Retry/RetrySyntaxAsync.cs
  src/Polly.Shared/Retry/RetryTResultSyntax.cs
  src/Polly.Shared/Retry/RetryTResultSyntaxAsync.cs
  src/Polly.SharedSpecs/Retry/RetryForeverAsyncSpecs.cs
  src/Polly.SharedSpecs/Retry/RetryForeverSpecs.cs
  src/Polly.SharedSpecs/Retry/WaitAndRetryForeverAsyncSpecs.cs
  src/Polly.SharedSpecs/Retry/WaitAndRetryForeverSpecs.cs
Labels: feature

#487 Merge v6.1.0 to master
  CHANGELOG.md
  GitVersionConfig.yaml
  README.md
  src/Polly.NetStandard11/Properties/AssemblyInfo.cs
  src/Polly.NetStandard20/Properties/AssemblyInfo.cs
  src/Polly.Shared/Caching/CachePolicy.cs
  src/Polly.Shared/Caching/CachePolicyAsync.cs
  src/Polly.Shared/Caching/GenericCacheProvider.cs
  src/Polly.Shared/Caching/GenericCacheProviderAsync.cs
  src/Polly.Shared/Caching/SerializingCacheProvider.cs
  src/Polly.Shared/Caching/SerializingCacheProviderAsync.cs
  src/Polly.Shared/Policy.Async.ExecuteOverloads.cs
  src/Polly.Shared/Policy.Async.TResult.ExecuteOverloads.cs
  src/Polly.Shared/Policy.ContextAndKeys.cs
  src/Polly.Shared/Policy.ExecuteOverloads.cs
  src/Polly.Shared/Policy.TResult.ExecuteOverloads.cs
  src/Polly.Shared/Polly.Shared.projitems
  src/Polly.Shared/Retry/RetryStateRetryForeverWithCount.cs
  src/Polly.Shared/Retry/RetryStateRetryForeverWithCountAsync.cs
  src/Polly.Shared/Retry/RetryStateWaitAndRetryForeverWithCount.cs
  src/Polly.Shared/Retry/RetryStateWaitAndRetryForeverWithCountAsync.cs
  src/Polly.Shared/Retry/RetrySyntax.cs
  src/Polly.Shared/Retry/RetrySyntaxAsync.cs
  src/Polly.Shared/Retry/RetryTResultSyntax.cs
  src/Polly.Shared/Retry/RetryTResultSyntaxAsync.cs
  src/Polly.Shared/Timeout/TimeoutEngine.cs
  src/Polly.Shared/Timeout/TimeoutEngineAsync.cs
  src/Polly.Shared/Timeout/TimeoutSyntax.cs
  src/Polly.Shared/Timeout/TimeoutSyntaxAsync.cs
  src/Polly.Shared/Timeout/TimeoutTResultSyntax.cs
  src/Polly.Shared/Timeout/TimeoutTResultSyntaxAsync.cs
  src/Polly.Shared/Wrap/PolicyWrap.ContextAndKeys.cs
  src/Polly.SharedSpecs/Caching/CacheAsyncSpecs.cs
  src/Polly.SharedSpecs/Caching/CacheSpecs.cs
  src/Polly.SharedSpecs/Caching/CacheTResultAsyncSpecs.cs
  src/Polly.SharedSpecs/Caching/CacheTResultSpecs.cs
  src/Polly.SharedSpecs/Caching/GenericCacheProviderAsyncSpecs.cs
  src/Polly.SharedSpecs/Caching/GenericCacheProviderSpecs.cs
  src/Polly.SharedSpecs/Caching/SerializingCacheProviderAsyncSpecs.cs
  src/Polly.SharedSpecs/Caching/SerializingCacheProviderSpecs.cs
  src/Polly.SharedSpecs/Polly.SharedSpecs.projitems
  src/Polly.SharedSpecs/Retry/RetryForeverAsyncSpecs.cs
  src/Polly.SharedSpecs/Retry/RetryForeverSpecs.cs
  src/Polly.SharedSpecs/Retry/WaitAndRetryForeverAsyncSpecs.cs
  src/Polly.SharedSpecs/Retry/WaitAndRetryForeverSpecs.cs
  src/Polly.SharedSpecs/Timeout/TimeoutAsyncSpecs.cs
  src/Polly.SharedSpecs/Timeout/TimeoutSpecs.cs
  src/Polly.SharedSpecs/Timeout/TimeoutTResultAsyncSpecs.cs
  src/Polly.SharedSpecs/Timeout/TimeoutTResultSpecs.cs
  src/Polly.SharedSpecs/Wrap/PolicyWrapContextAndKeySpecs.cs
  src/Polly.SharedSpecs/Wrap/PolicyWrapContextAndKeySpecsAsync.cs
  src/Polly.nuspec
Labels: bug, enhancement
