Repository App-vNext/Polly, pull requests merged in 2018-04, with the labels that each got.

#433 Add .AsPolicy<TResult> and .AsAsyncPolicy<TResult>
  CHANGELOG.md
  src/Polly.Net40Async.nuspec
  src/Polly.Shared/IAsyncPolicy.Extensions.cs
  src/Polly.Shared/ISyncPolicy.Extensions.cs
  src/Polly.Shared/Polly.Shared.projitems
  src/Polly.SharedSpecs/IAsyncPolicyExtensionsSpecs.cs
  src/Polly.SharedSpecs/ISyncPolicyExtensionsSpecs.cs
  src/Polly.SharedSpecs/Polly.SharedSpecs.projitems
  src/Polly.nuspec
Labels: enhancement, ready

#434 Update .net 4.0 specs comment
  src/Polly.Net40Async.Specs/readme.txt
Labels: ready

#437 Added new blog post by Scott Hanselman
  README.md
Labels: in progress

#439 Link to HttpClientFactory doco
  README.md
Labels: documentation, in progress
