Repository App-vNext/Polly, pull requests merged in 2019-02, with the labels that each got.

#577 Converted one liner methods to expression bodied members (Timeout).
  src/Polly.Shared/Timeout/AsyncTimeoutPolicy.cs
  src/Polly.Shared/Timeout/AsyncTimeoutSyntax.cs
  src/Polly.Shared/Timeout/AsyncTimeoutTResultSyntax.cs
  src/Polly.Shared/Timeout/TimeoutPolicy.cs
  src/Polly.Shared/Timeout/TimeoutSyntax.cs
  src/Polly.Shared/Timeout/TimeoutTResultSyntax.cs
Labels: code clean-ups

#578 Expose DelegateResult constructors, for use by custom policies.
  src/Polly.Shared/DelegateResult.cs
Labels: feature

#579 Adjust predicate and constructor visibility to support custom policies
  src/Polly.Shared/AsyncPolicy.TResult.cs
  src/Polly.Shared/AsyncPolicy.cs
  src/Polly.Shared/Bulkhead/AsyncBulkheadPolicy.cs
  src/Polly.Shared/Bulkhead/BulkheadPolicy.cs
  src/Polly.Shared/Caching/AsyncCachePolicy.cs
  src/Polly.Shared/Caching/CachePolicy.cs
  src/Polly.Shared/CircuitBreaker/AdvancedCircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/AdvancedCircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncAdvancedCircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncAdvancedCircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerPolicy.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/CircuitBreakerPolicy.cs
  src/Polly.Shared/CircuitBreaker/CircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/CircuitBreakerTResultSyntax.cs
  src/Polly.Shared/Fallback/AsyncFallbackPolicy.cs
  src/Polly.Shared/Fallback/AsyncFallbackSyntax.cs
  src/Polly.Shared/Fallback/FallbackPolicy.cs
  src/Polly.Shared/Fallback/FallbackSyntax.cs
  src/Polly.Shared/NoOp/AsyncNoOpPolicy.cs
  src/Polly.Shared/NoOp/NoOpPolicy.cs
  src/Polly.Shared/Policy.TResult.cs
  src/Polly.Shared/Policy.cs
  src/Polly.Shared/PolicyBase.cs
  src/Polly.Shared/PolicyBuilder.cs
  src/Polly.Shared/Retry/AsyncRetryPolicy.cs
  src/Polly.Shared/Retry/AsyncRetrySyntax.cs
  src/Polly.Shared/Retry/AsyncRetryTResultSyntax.cs
  src/Polly.Shared/Retry/RetryPolicy.cs
  src/Polly.Shared/Retry/RetrySyntax.cs
  src/Polly.Shared/Retry/RetryTResultSyntax.cs
  src/Polly.Shared/Timeout/AsyncTimeoutPolicy.cs
  src/Polly.Shared/Timeout/TimeoutPolicy.cs
  src/Polly.SharedSpecs/Helpers/Custom/AddBehaviourIfHandle/AddBehaviourIfHandlePolicy.cs
  src/Polly.SharedSpecs/Helpers/Custom/AddBehaviourIfHandle/AddBehaviourIfHandleSyntax.cs
  src/Polly.SharedSpecs/Helpers/Custom/AddBehaviourIfHandle/AsyncAddBehaviourIfHandlePolicy.cs
  src/Polly.SharedSpecs/Helpers/Custom/AddBehaviourIfHandle/AsyncAddBehaviourIfHandleSyntax.cs
  src/Polly.SharedSpecs/Helpers/Custom/PreExecute/AsyncPreExecutePolicy.cs
  src/Polly.SharedSpecs/Helpers/Custom/PreExecute/PreExecutePolicy.cs
Labels: feature

#582 Correctly state System.ValueTuple dependency for NetStandard 1.1 tfm
  CHANGELOG.md
  GitVersionConfig.yaml
  src/Polly.NetStandard11/Properties/AssemblyInfo.cs
  src/Polly.NetStandard20/Properties/AssemblyInfo.cs
  src/Polly.nuspec
Labels: packaging

#583 Updating list of videos
  README.md
Labels: documentation

#589 Fix issue 586. Set v7.0.3 details.
  CHANGELOG.md
  GitVersionConfig.yaml
  src/Polly.Shared/CircuitBreaker/AsyncAdvancedCircuitBreakerTResultSyntax.cs
  src/Polly.nuspec
Labels: bug fix

#596 Update README.md Cache example
  README.md
Labels: documentation

#597 Cache tweaks to readme
  README.md
Labels: documentation

#600 .gitignore mac and rider related files
  .gitignore
Labels: CI/build

#598 Converted one liner methods to expression bodied members (Utilities).
  src/Polly.Shared/Utilities/KeyHelper.cs
Labels: code clean-ups

#599 Converted one liner methods to expression bodied members (Wrap)
  src/Polly.Shared/Wrap/AsyncPolicyWrap.cs
  src/Polly.Shared/Wrap/AsyncPolicyWrapEngine.cs
  src/Polly.Shared/Wrap/IPolicyWrapExtension.cs
  src/Polly.Shared/Wrap/PolicyWrap.cs
  src/Polly.Shared/Wrap/PolicyWrapEngine.cs
Labels: code clean-ups
