Repository App-vNext/Polly, pull requests merged in 2019-11, with the labels that each got.

#715 Add TryAdd and TryRemove to PolicyRegistry
  src/Polly.Specs/Registry/PolicyRegistrySpecs.cs
  src/Polly/Registry/IPolicyRegistry.cs
  src/Polly/Registry/PolicyRegistry.cs
Labels: enhancement

#725 Fix, tests and doco for issue 620 - edge race case when timeout occurs while user exception is being marshalled
  CHANGELOG.md
  src/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutSpecs.cs
  src/Polly.Specs/Timeout/TimeoutSpecsBase.cs
  src/Polly/Timeout/AsyncTimeoutEngine.cs
  src/Polly/Timeout/TimeoutEngine.cs
Labels: bug fix

#726 Extensively refactor bulkhead tests
  src/Polly.Specs/Bulkhead/BulkheadAsyncSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadSpecsBase.cs
  src/Polly.Specs/Bulkhead/BulkheadSpecsHelper.cs
  src/Polly.Specs/Bulkhead/BulkheadTResultAsyncSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadTResultSpecs.cs
  src/Polly.Specs/Helpers/Bulkhead/AnnotatedOutputHelper.cs
  src/Polly.Specs/Helpers/Bulkhead/AssertionFailure.cs
  src/Polly.Specs/Helpers/Bulkhead/SilentOutputHelper.cs
  src/Polly.Specs/Helpers/Bulkhead/TraceableAction.cs
  src/Polly.Specs/Helpers/Bulkhead/TraceableActionStatus.cs
  src/Polly.Specs/Helpers/Constants.cs
Labels: unit-testing
