Repository App-vNext/Polly, pull requests merged in 2019-01, with the labels that each got.

#554 Make the IReadOnlyPolicyRegistry interface inherit IEnumerable
  CHANGELOG.md
  README.md
  src/Polly.NetStandard11.Specs/Polly.NetStandard11.Specs.csproj
  src/Polly.NetStandard20.Specs/Polly.NetStandard20.Specs.csproj
  src/Polly.Shared/Registry/IPolicyRegistry.cs
  src/Polly.Shared/Registry/IReadOnlyPolicyRegistry.cs
  src/Polly.Shared/Registry/PolicyRegistry.cs
  src/Polly.SharedSpecs/Registry/IReadOnlyPolicyRegistrySpecs.cs
  src/Polly.SharedSpecs/Registry/PolicyRegistrySpecs.cs
  src/Polly.nuspec
Labels: enhancement

#558 V7readmeimprovements
  README.md
Labels: documentation

#561 Change licenseUrl to license tag in nuspec file
  src/Polly.nuspec
Labels: documentation

#563 Adjusted tools path to fix build on OS X
  build.cake
Labels: CI/build

#565 Update README contributing guidelines
  README.md
Labels: documentation

#566 Changed to expression bodied members. Change to out variables.
  src/Polly.Shared/Registry/PolicyRegistry.cs
Labels: code clean-ups

#568 Added expression bodied members, null-ref checks (bulkhead policy)
  README.md
  src/Polly.Shared/Bulkhead/AsyncBulkheadSyntax.cs
  src/Polly.Shared/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly.Shared/Bulkhead/BulkheadPolicy.cs
  src/Polly.Shared/Bulkhead/BulkheadSyntax.cs
  src/Polly.Shared/Bulkhead/BulkheadTResultSyntax.cs
Labels: code clean-ups

#569 Added expression-bodied members (cache policy)
  src/Polly.Shared/Caching/AsyncCacheSyntax.cs
  src/Polly.Shared/Caching/AsyncCacheTResultSyntax.cs
  src/Polly.Shared/Caching/AsyncGenericCacheProvider.cs
  src/Polly.Shared/Caching/CachePolicy.cs
  src/Polly.Shared/Caching/CacheProviderExtensions.cs
  src/Polly.Shared/Caching/CacheSyntax.cs
  src/Polly.Shared/Caching/CacheTResultSyntax.cs
  src/Polly.Shared/Caching/DefaultCacheKeyStrategy.cs
  src/Polly.Shared/Caching/GenericCacheProvider.cs
  src/Polly.Shared/Caching/GenericTtlStrategy.cs
  src/Polly.Shared/Caching/ICachePolicy.cs
  src/Polly.Shared/Caching/NonSlidingTtl.cs
  src/Polly.Shared/Caching/RelativeTtl.cs
  src/Polly.Shared/Caching/ResultTtl.cs
  src/Polly.Shared/Caching/SlidingTtl.cs
  src/Polly.Shared/Caching/TtlStrategyExtensions.cs
Labels: code clean-ups

#572 Replaced one line methods with expression-bodied members. (Fallback)
  src/Polly.Shared/Fallback/AsyncFallbackPolicy.cs
  src/Polly.Shared/Fallback/FallbackPolicy.cs
  src/Polly.Shared/Fallback/IFallbackPolicy.cs
Labels: code clean-ups

#570 Replaced single line methods with expression-bodied members. (Circuit Breaker)
  src/Polly.Shared/CircuitBreaker/AdvancedCircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/AdvancedCircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/AdvancedCircuitController.cs
  src/Polly.Shared/CircuitBreaker/AsyncAdvancedCircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncAdvancedCircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerEngine.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerPolicy.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/AsyncCircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/BrokenCircuitException.cs
  src/Polly.Shared/CircuitBreaker/CircuitBreakerPolicy.cs
  src/Polly.Shared/CircuitBreaker/CircuitBreakerSyntax.cs
  src/Polly.Shared/CircuitBreaker/CircuitBreakerTResultSyntax.cs
  src/Polly.Shared/CircuitBreaker/CircuitStateController.cs
  src/Polly.Shared/CircuitBreaker/ConsecutiveCountCircuitController.cs
  src/Polly.Shared/CircuitBreaker/SingleHealthMetrics.cs
Labels: code clean-ups

#573 Refactored to expression bodied members (NoOp).
  src/Polly.Shared/NoOp/AsyncNoOpPolicy.cs
  src/Polly.Shared/NoOp/AsyncNoOpSyntax.cs
  src/Polly.Shared/NoOp/AsyncNoOpTResultSyntax.cs
  src/Polly.Shared/NoOp/INoOpPolicy.cs
  src/Polly.Shared/NoOp/NoOpEngine.cs
  src/Polly.Shared/NoOp/NoOpEngineAsync.cs
  src/Polly.Shared/NoOp/NoOpPolicy.cs
  src/Polly.Shared/NoOp/NoOpSyntax.cs
  src/Polly.Shared/NoOp/NoOpTResultSyntax.cs
Labels: code clean-ups

#574 Refactored to expression bodied members (Retry).
  src/Polly.Shared/Retry/AsyncRetryPolicy.cs
  src/Polly.Shared/Retry/AsyncRetrySyntax.cs
  src/Polly.Shared/Retry/AsyncRetryTResultSyntax.cs
  src/Polly.Shared/Retry/RetryPolicy.cs
  src/Polly.Shared/Retry/RetrySyntax.cs
  src/Polly.Shared/Retry/RetryTResultSyntax.cs
Labels: code clean-ups

#575 Expose Exception... and ResultPredicates, for custom policies
  src/Polly.Shared/PolicyBuilder.cs
Labels: feature

#576 Expose exception and result predicates to custom reactive policies
  src/Polly.Shared/AsyncPolicy.TResult.ExecuteOverloads.cs
  src/Polly.Shared/AsyncPolicy.TResult.cs
  src/Polly.Shared/AsyncPolicy.cs
  src/Polly.Shared/Policy.TResult.cs
  src/Polly.Shared/Policy.cs
  src/Polly.Shared/PolicyBase.cs
Labels: feature
