Repository App-vNext/Polly, pull requests merged in 2019-12, with the labels that each got.

#731 Readme updates
  README.md
Labels: documentation

#733 Update .csproj to enforce use of required Language version.
  src/Polly/Polly.csproj
Labels: CI/build

#738 Tweak AppVeyor build numbering to avoid failed builds
  build.cake
Labels: CI/build, bug fix
