Repository App-vNext/Polly, pull requests merged in 2019-10, with the labels that each got.

#681 Include symbols in package
  src/Polly/Polly.csproj
Labels: packaging

#695 use string Interpolation
  src/Polly.Specs/Bulkhead/BulkheadAsyncSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadTResultAsyncSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadTResultSpecs.cs
  src/Polly.Specs/Helpers/Bulkhead/TraceableAction.cs
  src/Polly/CircuitBreaker/AdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AdvancedCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerTResultSyntax.cs
Labels: code styling clean-ups

#697 fix some spelling
  src/Polly.Specs/Bulkhead/BulkheadAsyncSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadSpecsHelper.cs
  src/Polly.Specs/Bulkhead/BulkheadTResultAsyncSpecs.cs
  src/Polly.Specs/Bulkhead/BulkheadTResultSpecs.cs
  src/Polly.Specs/Caching/RelativeTtlSpecs.cs
  src/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerTResultAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerTResultSpecs.cs
  src/Polly.Specs/Fallback/FallbackAsyncSpecs.cs
  src/Polly.Specs/Fallback/FallbackSpecs.cs
  src/Polly.Specs/Fallback/FallbackTResultAsyncSpecs.cs
  src/Polly.Specs/Fallback/FallbackTResultSpecs.cs
  src/Polly.Specs/Retry/RetryAsyncSpecs.cs
  src/Polly.Specs/Retry/RetryForeverAsyncSpecs.cs
  src/Polly.Specs/Retry/RetrySpecs.cs
  src/Polly.Specs/Retry/RetryTResultSpecs.cs
  src/Polly.Specs/Retry/RetryTResultSpecsAsync.cs
  src/Polly.Specs/Retry/WaitAndRetryAsyncSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryForeverAsyncSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetrySpecs.cs
  src/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutSpecs.cs
  src/Polly.Specs/Timeout/TimeoutTResultAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutTResultSpecs.cs
  src/Polly/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly/Bulkhead/BulkheadTResultSyntax.cs
  src/Polly/Retry/RetrySyntax.cs
  src/Polly/Timeout/AsyncTimeoutSyntax.cs
  src/Polly/Timeout/AsyncTimeoutTResultSyntax.cs
  src/Polly/Timeout/TimeoutSyntax.cs
  src/Polly/Timeout/TimeoutTResultSyntax.cs
Labels: code styling clean-ups

#698 un used variables
  src/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerTResultSpecs.cs
  src/Polly.Specs/Fallback/FallbackSpecs.cs
  src/Polly.Specs/Fallback/FallbackTResultSpecs.cs
Labels: code styling clean-ups

#702 remove redundant field inits
  src/Polly.Specs/Helpers/PolicyExtensions.cs
  src/Polly.Specs/Helpers/PolicyExtensionsAsync.cs
  src/Polly.Specs/Timeout/TimeoutSpecsBase.cs
  src/Polly/Context.Dictionary.cs
Labels: code styling clean-ups

#703 remove redundant namespace in comments
  src/Polly/AsyncPolicy.ExecuteOverloads.cs
  src/Polly/AsyncPolicy.TResult.ExecuteOverloads.cs
  src/Polly/Bulkhead/AsyncBulkheadSyntax.cs
  src/Polly/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly/Bulkhead/BulkheadSyntax.cs
  src/Polly/Bulkhead/BulkheadTResultSyntax.cs
  src/Polly/Caching/AsyncSerializingCacheProvider.cs
  src/Polly/Caching/CacheSyntax.cs
  src/Polly/Caching/SerializingCacheProvider.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerTResultSyntax.cs
  src/Polly/Fallback/AsyncFallbackSyntax.cs
  src/Polly/Fallback/FallbackSyntax.cs
  src/Polly/IAsyncPolicy.TResult.cs
  src/Polly/IAsyncPolicy.cs
  src/Polly/ISyncPolicy.TResult.cs
  src/Polly/ISyncPolicy.cs
  src/Polly/Policy.ExecuteOverloads.cs
  src/Polly/Policy.TResult.ExecuteOverloads.cs
  src/Polly/PolicyBuilder.cs
  src/Polly/Registry/PolicyRegistry.cs
  src/Polly/Retry/AsyncRetrySyntax.cs
  src/Polly/Retry/AsyncRetryTResultSyntax.cs
  src/Polly/Retry/RetrySyntax.cs
  src/Polly/Retry/RetryTResultSyntax.cs
  src/Polly/Timeout/AsyncTimeoutSyntax.cs
  src/Polly/Timeout/AsyncTimeoutTResultSyntax.cs
  src/Polly/Timeout/TimeoutSyntax.cs
  src/Polly/Timeout/TimeoutTResultSyntax.cs
  src/Polly/Wrap/AsyncPolicyWrapSyntax.cs
  src/Polly/Wrap/PolicyWrapSyntax.cs
Labels: code styling clean-ups

#705 simplify some null checks
  src/Polly.Specs/Helpers/ContextualPolicyExtensions.cs
  src/Polly.Specs/Helpers/ContextualPolicyExtensionsAsync.cs
  src/Polly/CircuitBreaker/AdvancedCircuitController.cs
Labels: code styling clean-ups

#707 remove some redundant parentheses
  src/Polly.Specs/Caching/ResultTtlSpecs.cs
  src/Polly.Specs/PolicyAsyncSpecs.cs
  src/Polly.Specs/PolicySpecs.cs
  src/Polly.Specs/PolicyTResultAsyncSpecs.cs
  src/Polly.Specs/PolicyTResultSpecs.cs
Labels: code styling clean-ups

#709 remove some redundant namespace qualifiers
  src/Polly.Specs/Caching/AbsoluteTtlSpecs.cs
  src/Polly.Specs/Caching/CacheAsyncSpecs.cs
  src/Polly.Specs/Caching/CacheSpecs.cs
  src/Polly.Specs/Caching/CacheTResultAsyncSpecs.cs
  src/Polly.Specs/Caching/CacheTResultSpecs.cs
  src/Polly.Specs/Caching/GenericCacheProviderAsyncSpecs.cs
  src/Polly.Specs/Caching/GenericCacheProviderSpecs.cs
  src/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerTResultAsyncSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerTResultMixedResultExceptionSpecs.cs
  src/Polly.Specs/CircuitBreaker/CircuitBreakerTResultSpecs.cs
  src/Polly.Specs/Helpers/Custom/PreExecute/PreExecutePolicy.cs
  src/Polly.Specs/Retry/WaitAndRetryForeverAsyncSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryForeverSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryForeverTResultAsyncSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryForeverTResultSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetrySpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryTResultAsyncSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryTResultSpecs.cs
  src/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutSpecs.cs
  src/Polly.Specs/Timeout/TimeoutTResultAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutTResultSpecs.cs
  src/Polly.Specs/Wrap/PolicyWrapContextAndKeySpecs.cs
  src/Polly.Specs/Wrap/PolicyWrapContextAndKeySpecsAsync.cs
  src/Polly.Specs/Wrap/PolicyWrapSpecs.cs
  src/Polly.Specs/Wrap/PolicyWrapSpecsAsync.cs
  src/Polly/PolicyBuilder.cs
  src/Polly/Utilities/TimedLock.cs
Labels: code styling clean-ups

#701 remove strange string split in PolicyContextAndKeySpecs.cs
  src/Polly.Specs/PolicyContextAndKeySpecs.cs
Labels: code styling clean-ups

#708 use lambda expressions where possible
  src/Polly.Specs/Caching/CacheSpecs.cs
  src/Polly.Specs/Caching/CacheTResultSpecs.cs
  src/Polly.Specs/Caching/GenericCacheProviderSpecs.cs
  src/Polly.Specs/Caching/ResultTtlSpecs.cs
  src/Polly.Specs/Fallback/FallbackAsyncSpecs.cs
  src/Polly.Specs/Fallback/FallbackSpecs.cs
  src/Polly.Specs/Fallback/FallbackTResultAsyncSpecs.cs
  src/Polly.Specs/Fallback/FallbackTResultSpecs.cs
  src/Polly.Specs/PolicyAsyncSpecs.cs
  src/Polly.Specs/PolicySpecs.cs
  src/Polly.Specs/Retry/RetryAsyncSpecs.cs
  src/Polly.Specs/Retry/RetrySpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryAsyncSpecs.cs
  src/Polly.Specs/Retry/WaitAndRetryForeverAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutSpecs.cs
  src/Polly.Specs/Timeout/TimeoutTResultAsyncSpecs.cs
  src/Polly.Specs/Timeout/TimeoutTResultSpecs.cs
Labels: code styling clean-ups

#694 add Directory.Build.props
  src/Directory.Build.props
  src/Polly.Specs/Polly.Specs.csproj
  src/Polly/Polly.csproj
Labels: packaging

#704 simplify some defaults
  src/Polly.Specs/Caching/CacheAsyncSpecs.cs
  src/Polly.Specs/Caching/CacheSpecs.cs
  src/Polly.Specs/Caching/CacheTResultAsyncSpecs.cs
  src/Polly.Specs/Caching/CacheTResultSpecs.cs
  src/Polly.Specs/Caching/SerializingCacheProviderAsyncSpecs.cs
  src/Polly.Specs/Caching/SerializingCacheProviderSpecs.cs
  src/Polly.Specs/Helpers/Bulkhead/TraceableAction.cs
  src/Polly.Specs/Helpers/ContextualPolicyExtensionsAsync.cs
  src/Polly.Specs/Helpers/PolicyExtensionsAsync.cs
  src/Polly.Specs/Helpers/PolicyTResultExtensionsAsync.cs
  src/Polly/Caching/AsyncCacheEngine.cs
  src/Polly/Caching/AsyncSerializingCacheProvider.cs
  src/Polly/Caching/CacheEngine.cs
  src/Polly/Caching/SerializingCacheProvider.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/CircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/CircuitStateController.cs
  src/Polly/PolicyResult.cs
  src/Polly/Registry/PolicyRegistry.cs
Labels: code styling clean-ups

#714 Remove some redundant casts
  src/Polly/Caching/GenericTtlStrategy.cs
  src/Polly/Registry/PolicyRegistry.cs
Labels: code styling clean-ups

#696 also run tests on netcore3
  appveyor.yml
  src/Polly.Specs/Polly.Specs.csproj
Labels: target frameworks

#716 Simplify bulkhead semaphore creation
  src/Polly/Bulkhead/AsyncBulkheadPolicy.cs
  src/Polly/Bulkhead/AsyncBulkheadSyntax.cs
  src/Polly/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly/Bulkhead/BulkheadPolicy.cs
  src/Polly/Bulkhead/BulkheadSemaphoreFactory.cs
  src/Polly/Bulkhead/BulkheadSyntax.cs
  src/Polly/Bulkhead/BulkheadTResultSyntax.cs
Labels: code styling clean-ups
