Repository App-vNext/Polly, pull requests merged in 2023-09, with the labels that each got.

#1539 Cleanup the Polly.Core README.md
  src/Polly.Core/README.md
  src/Polly.Core/ResilienceStrategy.TResult.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Extensions/README.md
  src/Polly.RateLimiting/README.md
Labels: documentation, v8

#1542 Add actionlint
  .github/actionlint-matcher.json
  .github/workflows/actions-lint.yml
Labels: enhancement, CI/build, v8, github_actions

#1544 Cleanup samples
  samples/DependencyInjection/Program.cs
  samples/Directory.Build.props
  samples/Extensibility/Program.cs
  samples/GenericStrategies/Program.cs
  samples/Intro/Program.cs
  samples/Retries/ExecuteHelper.cs
  samples/Retries/Program.cs
  samples/Samples.sln
Labels: v8

#1540 Move code from markdown to snippets
  .config/dotnet-tools.json
  .github/workflows/on-push-do-docs.yml
  Directory.Packages.props
  Polly.sln
  bench/README.md
  build.cake
  mdsnippets.json
  src/Polly.Core/README.md
  src/Polly.Extensions/README.md
  src/Polly.RateLimiting/README.md
  src/Polly.Testing/README.md
  src/Snippets/Core/Snippets.cs
  src/Snippets/Extensions/Snippets.cs
  src/Snippets/README.md
  src/Snippets/RateLimiting/Snippets.cs
  src/Snippets/Snippets.csproj
  src/Snippets/Testing/Snippets.cs
Labels: v8

#1552 Use proactive term instead of non-reactive
  src/Polly.Core/README.md
  src/Polly.Core/ResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/ResilienceStrategy.cs
Labels: v8

#1548 Add the v8 README.md
  README.md
  README_V8.md
  docs/README.md
  docs/dependency-injection.md
  docs/extensiblity.md
  docs/general.md
  docs/resilience-context.md
  docs/resilience-pipeline-registry.md
  docs/resilience-pipelines.md
  docs/resilience-strategies.md
  docs/simmy.md
  docs/telemetry.md
  src/Polly.Core/README.md
  src/Snippets/Docs/CircuitBreaker.cs
  src/Snippets/Docs/Fallback.cs
  src/Snippets/Docs/General.cs
  src/Snippets/Docs/Hedging.cs
  src/Snippets/Docs/RateLimiter.cs
  src/Snippets/Docs/Readme.cs
  src/Snippets/Docs/ResilienceContextUsage.cs
  src/Snippets/Docs/ResiliencePipelines.cs
  src/Snippets/Docs/ResilienceStrategies.cs
  src/Snippets/Docs/Retry.cs
  src/Snippets/Docs/Timeout.cs
  src/Snippets/Docs/Utils/SomeExceptionType.cs
  src/Snippets/Snippets.csproj
Labels: v8

#1554 Use token to clone repository
  .github/workflows/on-push-do-docs.yml
Labels: bug, github_actions

#1553 [Docs] Add docs for individual resilience strategies
  README_V8.md
  docs/README.md
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/hedging.md
  docs/strategies/rate-limiter.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  src/Snippets/Docs/CircuitBreaker.cs
  src/Snippets/Docs/Fallback.cs
  src/Snippets/Docs/Hedging.cs
  src/Snippets/Docs/RateLimiter.cs
  src/Snippets/Docs/Retry.cs
  src/Snippets/Docs/Timeout.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/ScheduledTaskExecutorTests.cs
Labels: v8

#1557 [Docs] Fix v8 link
  README.md
Labels: v8

#1559 Fix the link to v8 docs (second attempt)
  README.md
Labels: v8

#1562 Improve the samples
  samples/GenericPipelines/GenericPipelines.csproj
  samples/GenericPipelines/Program.cs
  samples/README.md
  samples/Samples.sln
Labels: v8

#1560 [Docs] Hedging and rate limiter strategy docs
  README_V8.md
  docs/resilience-strategies.md
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/hedging.md
  docs/strategies/rate-limiter.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  src/Snippets/Docs/Hedging.cs
  src/Snippets/Docs/RateLimiter.cs
Labels: v8

#1564 [Docs] Dependency injection
  docs/dependency-injection.md
  docs/strategies/hedging.md
  src/Polly.Extensions/README.md
  src/Snippets/Docs/DependencyInjection.cs
  src/Snippets/Docs/Hedging.cs
  src/Snippets/Docs/Telemetry.cs
  src/Snippets/Extensions/Snippets.cs
Labels: v8

#1566 [Docs] Improve landing page to the docs
  docs/README.md
Labels: v8

#1572 Drop the build target for net7.0
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.RateLimiting/Polly.RateLimiting.csproj
  src/Polly/Polly.csproj
Labels: v8

#1573 Drop redundant System.Diagnostics.DiagnosticSource package reference
  src/Polly.Core/Polly.Core.csproj
Labels: v8

#1574 Improve the docs and behavior around infinite retries
  README_V8.md
  docs/strategies/retry.md
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Snippets/Docs/Retry.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
Labels: v8

#1575 [Docs] Resilience pipeline registry
  docs/resilience-pipeline-registry.md
  docs/strategies/hedging.md
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Snippets/Docs/Hedging.cs
  src/Snippets/Docs/ResiliencePipelineRegistry.cs
  src/Snippets/Snippets.csproj
Labels: v8

#1576 [Docs] Consolidate headings
  docs/README.md
  docs/resilience-context.md
  docs/resilience-strategies.md
Labels: v8

#1580 Updates for beta.2
  CHANGELOG.md
  Directory.Packages.props
  README.md
Labels: v8

#1586 Re-run the benchmarks
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.BridgeBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerOpenedBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CreationBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.GenericOverheadBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.HedgingBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PipelineBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PredicateBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RateLimiterBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResiliencePipelineBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResiliencePipelineProviderBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RetryBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TelemetryBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TimeoutBenchmark-report-github.md
Labels: v8

#1593 Adds gh-pages support
  .config/dotnet-tools.json
  .github/workflows/gh-pages.yml
  README.md
  README_V8.md
  docs/.gitignore
  docs/README.md
  docs/advanced/telemetry.md
  docs/api/.gitignore
  docs/api/index.md
  docs/docfx.json
  docs/getting-started.md
  docs/icon.png
  docs/index.md
  docs/migration-v8.md
  docs/pipelines/index.md
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/hedging.md
  docs/strategies/index.md
  docs/strategies/rate-limiter.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  docs/toc.yml
Labels: documentation, v8

#1596 Don't publish docs on PRs
  .github/workflows/gh-pages.yml
Labels: v8

#1592 Fix some XML docs inaccuracies
  src/Polly.Extensions/DependencyInjection/AddResiliencePipelineContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Registry/ConfigureBuilderContextExtensions.cs
Labels: v8

#1598 Migration guide from v7 to v8
  README_V8.md
  docs/advanced/resilience-context.md
  docs/index.md
  docs/migration-v8.md
  docs/strategies/circuit-breaker.md
  docs/strategies/hedging.md
  docs/strategies/rate-limiter.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  src/Snippets/Core/Snippets.cs
  src/Snippets/Docs/CircuitBreaker.cs
  src/Snippets/Docs/DependencyInjection.cs
  src/Snippets/Docs/Fallback.cs
  src/Snippets/Docs/General.cs
  src/Snippets/Docs/Hedging.cs
  src/Snippets/Docs/Migration.Bulkhead.cs
  src/Snippets/Docs/Migration.Context.cs
  src/Snippets/Docs/Migration.Interoperability.cs
  src/Snippets/Docs/Migration.Policies.cs
  src/Snippets/Docs/Migration.RateLimiter.cs
  src/Snippets/Docs/Migration.Registry.cs
  src/Snippets/Docs/Migration.Retry.cs
  src/Snippets/Docs/Migration.Wrap.cs
  src/Snippets/Docs/RateLimiter.cs
  src/Snippets/Docs/Readme.cs
  src/Snippets/Docs/ResilienceContextUsage.cs
  src/Snippets/Docs/ResiliencePipelineRegistry.cs
  src/Snippets/Docs/ResiliencePipelines.cs
  src/Snippets/Docs/ResilienceStrategies.cs
  src/Snippets/Docs/Retry.cs
  src/Snippets/Docs/Telemetry.cs
  src/Snippets/Docs/Timeout.cs
  src/Snippets/RateLimiting/Snippets.cs
  src/Snippets/Snippets.csproj
  src/Snippets/Testing/Snippets.cs
  test/Polly.Core.Tests/Utils/CancellationTokenSourcePoolTests.cs
Labels: v8

#1600 [Docs] Introduce Performance article
  README_V8.md
  docs/advanced/performance.md
  docs/getting-started.md
  docs/index.md
  docs/toc.yml
  src/Snippets/Docs/Performance.cs
  src/Snippets/Docs/Readme.cs
  src/Snippets/Snippets.csproj
Labels: v8

#1602 [Docs] General extensibility and implementation of proactive strategies
  docs/advanced/extensibility.md
  docs/extensibility/index.md
  docs/extensibility/proactive-strategy.md
  docs/extensibility/reactive-strategy.md
  docs/index.md
  docs/toc.yml
  samples/Extensibility/Proactive/ThresholdExceededArguments.cs
  samples/Extensibility/Proactive/TimingResilienceStrategy.cs
  samples/Extensibility/Proactive/TimingResilienceStrategyBuilderExtensions.cs
  samples/Extensibility/Proactive/TimingStrategyOptions.cs
  samples/Extensibility/Program.cs
  src/Polly.Core/README.md
  src/Snippets/Core/Snippets.cs
  src/Snippets/Docs/Extensibility.cs
Labels: v8

#1583 Align the telemetry tags with official guidelines
  docs/advanced/telemetry.md
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryListenerImpl.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/StrategyBuilderContextTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1606 [Docs] Reactive strategies extensibility
  docs/extensibility/proactive-strategy.md
  docs/extensibility/reactive-strategy.md
  docs/general.md
  samples/Extensibility/Proactive/TimingResilienceStrategyBuilderExtensions.cs
  samples/Extensibility/Program.cs
  samples/Extensibility/Reactive/OnReportResultArguments.cs
  samples/Extensibility/Reactive/ResultReportingPredicateArguments.cs
  samples/Extensibility/Reactive/ResultReportingResilienceStrategy.cs
  samples/Extensibility/Reactive/ResultReportingResilienceStrategyBuilderExtensions.cs
  samples/Extensibility/Reactive/ResultReportingStrategyOptions.cs
  src/Snippets/Docs/General.cs
Labels: documentation, v8

#1608 [Docs] Testing
  docs/advanced/testing.md
  docs/index.md
  docs/toc.yml
  src/Polly.RateLimiting/README.md
  src/Polly.Testing/README.md
  src/Snippets/Docs/Testing.cs
  src/Snippets/RateLimiting/Snippets.cs
  src/Snippets/Snippets.csproj
  src/Snippets/Testing/Snippets.cs
Labels: documentation, v8

#1618 [Docs] Performance docs improvements
  docs/advanced/performance.md
  src/Snippets/Docs/Performance.cs
Labels: documentation, v8

#1619 [Docs] Polish the docs
  docs/strategies/fallback.md
  docs/strategies/retry.md
  src/Snippets/Docs/Retry.cs
Labels: documentation

#1620 Introduce `RetryStrategyOptions.MaxDelay` property
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
Labels: v8

#1623 Use SHA256 for ChecksumAlgorithm and fix Binskim warning
  eng/Library.targets
Labels: v8

#1628 Harden gh-pages workflow
  .github/workflows/gh-pages.yml
Labels: documentation, dependencies, github_actions

#1626 Update README
  README.md
  README_V8.md
Labels: documentation, v8

#1622 [Docs] Timeout policy migration
  docs/migration-v8.md
  src/Snippets/Docs/Migration.Timeout.cs
Labels: documentation, v8

#1625 Fix the behavior of `OnHedging` event
  src/Polly.Core/Hedging/Controller/HedgingHandler.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  test/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingHelper.cs
  test/Polly.Core.Tests/Hedging/HedgingResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/OnHedgingArgumentsTests.cs
Labels: v8

#1629 Fix typo
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
Labels: documentation, v8

#1634 [Docs] Update some README links to point to pollydocs.org
  README_V8.md
Labels: documentation, v8

#1631 [Docs] Document Retry's `MaxDelay` property
  docs/strategies/retry.md
  src/Snippets/Docs/Retry.cs
Labels: v8

#1637 Bump actionlint
  .github/workflows/actions-lint.yml
Labels: dependencies, github_actions

#1638 [Docs] Add safe execution section to the migration guide
  docs/migration-v8.md
  src/Snippets/Docs/Migration.Execute.cs
Labels: documentation, v8

#1642 Add OSSF scorecard badge
  README_V8.md
Labels: enhancement, documentation, v8

#1643 Bump xunit.runner.console
  build.cake
Labels: CI/build, dependencies, v8

#1645 Update CHANGELOG for 8.0.0
  CHANGELOG.md
Labels: documentation, v8

#1641 Update docs source
  docs/strategies/fallback.md
  src/Snippets/Docs/Fallback.cs
Labels: documentation, v8

#1644 Stabilize `AddHedging_IntegrationTest` test
  test/Polly.Core.Tests/Hedging/HedgingResiliencePipelineBuilderExtensionsTests.cs
Labels: v8

#1599 Release v8 docs
  README.md
  README_V8.md
  docs/advanced/resilience-context.md
  docs/general.md
  docs/index.md
  docs/pipelines/index.md
  docs/strategies/index.md
  package-readme.md
Labels: documentation, v8

#1648 Update CHANGELOG
  CHANGELOG.md
Labels: documentation, v8

#1649 Only show stable versions in README
  README.md
Labels: documentation, v8

#1647 Update samples to stable release
  Directory.Packages.props
Labels: dependencies, v8

#1632 v8 Release - commit and validate public API
  eng/Library.targets
  samples/Directory.Build.props
  src/Polly.Core/PublicAPI.Shipped.txt
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Extensions/PublicAPI.Shipped.txt
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/PublicAPI.Shipped.txt
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.Testing/PublicAPI.Shipped.txt
  src/Polly.Testing/PublicAPI.Unshipped.txt
  src/Polly/PublicAPI.Shipped.txt
  src/Polly/PublicAPI.Unshipped.txt
  src/Snippets/Snippets.csproj
  test/Polly.TestUtils/Polly.TestUtils.csproj
Labels: v8

#1654 Fix documentation comment for CB's MinimumThroughput
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.TResult.cs
Labels: documentation, bug fix

#1655 Docs tweaks
  docs/community/polly-contrib.md
  docs/docfx.json
  docs/getting-started.md
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  eng/Common.targets
  eng/Library.targets
Labels: enhancement, documentation

#1666 Add Github repo link to the docs navbar
  docs/docfx.json
  docs/template/public/main.js
Labels: enhancement, documentation

#1664 Add markdownlint
  .github/ISSUE_TEMPLATE/bug-.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/how-to.md
  .github/ISSUE_TEMPLATE/request.md
  .github/pull_request_template.md
  .github/workflows/gh-pages.yml
  .markdownlint.json
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  docs/advanced/dependency-injection.md
  docs/api/index.md
Labels: enhancement, documentation, CI/build, dependencies, github_actions
