Repository App-vNext/Polly, pull requests merged in 2023-01, with the labels that each got.

#992 #944- Added to readme explaining waitand/retryforever is not actually…
  README.md
Labels: documentation

#993 Remove AppVeyor build
  README.md
  appveyor.yml
  build.cake
  src/Polly.sln
Labels: enhancement, CI/build

#995 Upload code coverage to codecov.io
  .config/dotnet-tools.json
  .github/ISSUE_TEMPLATE/how-to.md
  .github/workflows/build.yml
  .gitignore
  README.md
  build.cake
  build.ps1
  src/Polly.Benchmarks/Polly.Benchmarks.csproj
  src/Polly.Specs/Polly.Specs.csproj
  src/Polly/Polly.csproj
Labels: enhancement, CI/build

#996 Build on Linux and macOS
  .config/dotnet-tools.json
  .github/workflows/build.yml
  build.cake
  build.ps1
  src/Polly.Specs/Polly.Specs.csproj
Labels: enhancement, CI/build

#1004 Add dependabot updates
  .github/dependabot.yml
Labels: CI/build

#1005 Add GitHub Actions workflow to update the .NET SDK
  .github/workflows/update-dotnet-sdk.yml
Labels: CI/build

#1016 Use dotnet add instead of Install-Package
  README.md
Labels: enhancement, documentation
