Repository App-vNext/Polly, pull requests merged in 2023-11, with the labels that each got.

#1764 [Docs] Add circuit breaker to the migration guide
  docs/migration-v8.md
  docs/strategies/circuit-breaker.md
  src/Snippets/Docs/CircuitBreaker.cs
  src/Snippets/Docs/Migration.CircuitBreaker.cs
  src/Snippets/Docs/Migration.Retry.cs
Labels: documentation

#1767 [Docs] Improve timeout docs
  docs/strategies/timeout.md
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Snippets/Docs/Timeout.cs
Labels: documentation

#1776 Calculated break duration for Circuit breaker
  src/Polly.Core/CircuitBreaker/BreakDurationGeneratorArguments.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/Controller/AdvancedCircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/CircuitBreaker/Health/HealthInfo.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  test/Polly.Core.Tests/CircuitBreaker/BreakDurationGeneratorArgumentsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/AdvancedCircuitBehaviorTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Health/HealthMetricsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Health/RollingHealthMetricsTests.cs
Labels: enhancement

#1781 Disable GitHub publishing
  .github/workflows/build.yml
Labels: CI/build

#1782 [Docs] Small cleanup and improvements
  docs/advanced/dependency-injection.md
  docs/advanced/resilience-context.md
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  src/Snippets/Docs/DependencyInjection.cs
Labels: documentation

#1789 Remove GitHub Packages publishing
  .github/workflows/build.yml
Labels: CI/build

#1795 Allow concurrent PR docs builds
  .github/workflows/gh-pages.yml
Labels: CI/build

#1796 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1738 Update to .NET 8 SDK
  .github/workflows/build.yml
  Directory.Build.props
  build.cake
  eng/stryker-config.json
  global.json
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  src/Polly.Core/CompatibilitySuppressions.xml
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Core/PredicateBuilder.TResult.cs
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/Utils/Pipeline/ReloadableComponent.cs
  src/Polly.Extensions/DependencyInjection/ConfigureResiliencePipelineRegistryOptions.cs
  src/Polly/AsyncPolicy.ExecuteOverloads.cs
  src/Polly/AsyncPolicy.TResult.ExecuteOverloads.cs
  src/Polly/CompatibilitySuppressions.xml
  src/Polly/Context.Dictionary.cs
  src/Polly/ExceptionPredicates.cs
  src/Polly/Policy.ExecuteOverloads.cs
  src/Polly/Policy.TResult.ExecuteOverloads.cs
  src/Polly/ResultPredicates.cs
  test/Polly.AotTest/Polly.AotTest.csproj
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActions.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Async.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Sync.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.cs
  test/Polly.Core.Tests/Retry/RetryResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Simmy/Behavior/BehaviorChaosStrategyTests.cs
  test/Polly.Core.Tests/Simmy/Fault/FaultChaosPipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Simmy/Fault/FaultChaosStrategyTests.cs
  test/Polly.Core.Tests/Simmy/Latency/LatencyChaosStrategyTests.cs
  test/Polly.Core.Tests/Simmy/Outcomes/OutcomeChaosPipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Simmy/Outcomes/OutcomeChaosStrategyTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutTestUtils.cs
  test/Polly.Core.Tests/Utils/Pipeline/ReloadablePipelineComponentTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  test/Polly.Specs/ContextSpecs.cs
  test/Polly.Specs/Helpers/Caching/StubCacheProvider.cs
  test/Polly.Specs/RateLimit/RateLimitPolicyTResultSpecsBase.cs
  test/Polly.TestUtils/FakeLogger.cs
Labels: CI/build, dependencies, .NET

#1798 Bump version to 8.3.0
  Directory.Packages.props
  eng/Common.targets
  eng/Library.targets
  src/Polly.Core/PublicAPI.Shipped.txt
  src/Polly.Core/PublicAPI.Unshipped.txt
Labels: CI/build

#1800 Publish AoT for test on macOS
  test/Polly.AotTest/Polly.AotTest.csproj
Labels: CI/build

#1809 Remove SourceLink package
  Directory.Packages.props
  eng/Library.targets
Labels: CI/build, dependencies

#1810 Pre-allocate list size in tests
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
Labels: CI/build

#1811 Update tools
  build.cake
Labels: dependencies, .NET

#1813 Add NuGet package descriptions
  eng/Library.targets
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.RateLimiting/Polly.RateLimiting.csproj
  src/Polly.Testing/Polly.Testing.csproj
  src/Polly/Polly.csproj
Labels: CI/build, bug fix

#1822 Bump dotnet-stryker to 3.12.0
  build.cake
  eng/stryker-config.json
Labels: CI/build, dependencies, .NET

#1821 Add link to Polly stream
  docs/community/resources.md
Labels: documentation

#1820 Fix spacing
  README.md
  docs/getting-started.md
  src/Snippets/Docs/Readme.cs
Labels: documentation

#1819 [Docs] Couple of minor corrections
  README.md
  docs/getting-started.md
  docs/migration-v8.md
  docs/strategies/index.md
  src/Snippets/Docs/Readme.cs
  src/Snippets/Docs/ResilienceStrategies.cs
Labels: documentation

#1830 Add .NET Blog resilience blog post
  docs/community/resources.md
Labels: documentation

#1831 [Docs] Update circuit-breaker docs for HTTP scenarios
  Directory.Packages.props
  docs/strategies/circuit-breaker.md
  src/Snippets/Docs/CircuitBreaker.cs
  src/Snippets/Snippets.csproj
Labels: documentation
