Repository App-vNext/Polly, pull requests merged in 2023-12, with the labels that each got.

#1836 [Docs] Add timeout and fallback cheat sheets
  docs/community/cheat-sheets.md
  docs/docfx.json
  docs/media/Fallback-cheat-sheet.pdf
  docs/media/Fallback-cheat-sheet.pptx
  docs/media/Timeout-cheat-sheet.pdf
  docs/media/Timeout-cheat-sheet.pptx
  docs/toc.yml
Labels: documentation

#1840 Update Cheat Sheet table
  docs/community/cheat-sheets.md
Labels: documentation

#1846 [Docs] Add hedging cheat sheet
  docs/community/cheat-sheets.md
  docs/media/cheat-sheet-hedging.pdf
  docs/media/cheat-sheet-hedging.pptx
Labels: documentation

#1849 Update NuGet packages
  .config/dotnet-tools.json
  Directory.Packages.props
  src/Polly.Core/Utils/Pipeline/ReloadableComponent.cs
  src/Polly.RateLimiting/RateLimiterResiliencePipelineBuilderExtensions.cs
Labels: dependencies, .NET

#1808 update circuitbreaker document
  README.md
  docs/strategies/circuit-breaker.md
  src/Snippets/Docs/CircuitBreaker.cs
Labels: documentation

#1861 Update Git workflow
  docs/community/git-workflow.md
Labels: enhancement, documentation

#1862 [Docs] Revise proactive strategy doc
  docs/extensibility/index.md
  docs/extensibility/proactive-strategy.md
  samples/Extensibility/Proactive/OnThresholdExceededArguments.cs
  samples/Extensibility/Proactive/TimingResilienceStrategy.cs
  samples/Extensibility/Proactive/TimingResilienceStrategyBuilderExtensions.cs
  samples/Extensibility/Proactive/TimingStrategyOptions.cs
  samples/Extensibility/Program.cs
Labels: documentation

#1863 [Docs] Revise reactive strategy sample
  docs/extensibility/reactive-strategy.md
  samples/Extensibility/Extensibility.csproj
  samples/Extensibility/Program.cs
  samples/Extensibility/Reactive/OnReportResultArguments.cs
  samples/Extensibility/Reactive/ResultReportingPredicateArguments.cs
  samples/Extensibility/Reactive/ResultReportingResilienceStrategy.cs
  samples/Extensibility/Reactive/ResultReportingResilienceStrategyBuilderExtensions.cs
  samples/Extensibility/Reactive/ResultReportingStrategyOptions.cs
Labels: documentation

#1873 Bump xunit
  Directory.Packages.props
Labels: dependencies, .NET
