Repository App-vNext/Polly, pull requests merged in 2023-03, with the labels that each got.

#1052 Add coverage summaries in Actions
  src/Polly.Specs/Polly.Specs.csproj
Labels: enhancement, CI/build

#1073 Introduce ResilienceTelemetryFactory
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderContextTests.cs
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/Telemetry/NullResilienceTelemetryFactoryTests.cs
  src/Polly.Core.Tests/Telemetry/NullResilienceTelemetryTests.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilder.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilderOptions.cs
  src/Polly.Core/Telemetry/NullResilienceTelemetry.cs
  src/Polly.Core/Telemetry/NullResilienceTelemetryFactory.cs
  src/Polly.Core/Telemetry/ResilienceTelemetry.cs
  src/Polly.Core/Telemetry/ResilienceTelemetryFactory.cs
  src/Polly.Core/Telemetry/ResilienceTelemetryFactoryContext.cs
Labels: v8

#1076 Fix coverage upload
  .github/workflows/build.yml
  build.cake
  eng/Test.targets
Labels: bug, CI/build

#1077 Introduce TimeProvider
  eng/Library.targets
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderOptionsTests.cs
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/Utils/FakeTimeProvider.cs
  src/Polly.Core.Tests/Utils/SystemTimeProviderTests.cs
  src/Polly.Core.Tests/Utils/TestUtils.cs
  src/Polly.Core.Tests/Utils/TimeProviderExtensionsTests.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilder.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilderOptions.cs
  src/Polly.Core/Utils/TimeProvider.cs
  src/Polly.Core/Utils/TimeProviderExtensions.cs
Labels: v8

#1082 Ignore some dependabot updates
  .github/dependabot.yml
Labels: CI/build

#1079 Introduce Timeout Strategy
  eng/Test.targets
  eng/analyzers/Library.globalconfig
  eng/analyzers/Test.globalconfig
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderContextTests.cs
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderOptionsTests.cs
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/Builder/ResilienceStrategyOptionsTests.cs
  src/Polly.Core.Tests/Builder/ResilienceStrategyPipelineTests.cs
  src/Polly.Core.Tests/ExecutionRejectedExceptionTests.cs
  src/Polly.Core.Tests/NullResilienceStrategyTests.cs
  src/Polly.Core.Tests/Polly.Core.Tests.csproj
  src/Polly.Core.Tests/ResilienceContextTests.cs
  src/Polly.Core.Tests/ResiliencePropertiesTests.cs
  src/Polly.Core.Tests/ResiliencePropertyKeyTests.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.Task.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.TaskT.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.ValueTask.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.ValueTaskT.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Sync.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.SyncT.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.cs
  src/Polly.Core.Tests/Telemetry/NullResilienceTelemetryFactoryTests.cs
  src/Polly.Core.Tests/Telemetry/NullResilienceTelemetryTests.cs
  src/Polly.Core.Tests/Timeout/OnTimeoutEventTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutAttributeTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutConstantsTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutGeneratorTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutRejectedExceptionTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutStrategyOptionsTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutTestUtils.cs
  src/Polly.Core.Tests/Timeout/TimeoutUtilTests.cs
  src/Polly.Core.Tests/Utils/BinarySerializationUtil.cs
  src/Polly.Core.Tests/Utils/FakeTimeProvider.cs
  src/Polly.Core.Tests/Utils/SynchronousExecutionHelperTests.cs
  src/Polly.Core.Tests/Utils/SystemTimeProviderTests.cs
  src/Polly.Core.Tests/Utils/TestUtils.cs
  src/Polly.Core.Tests/Utils/TimeProviderExtensionsTests.cs
  src/Polly.Core/ExecutionRejectedException.cs
  src/Polly.Core/Strategy/IResilienceArguments.cs
  src/Polly.Core/Timeout/OnTimeoutArguments.cs
  src/Polly.Core/Timeout/OnTimeoutEvent.cs
  src/Polly.Core/Timeout/TimeoutAttribute.cs
  src/Polly.Core/Timeout/TimeoutConstants.cs
  src/Polly.Core/Timeout/TimeoutGenerator.cs
  src/Polly.Core/Timeout/TimeoutGeneratorArguments.cs
  src/Polly.Core/Timeout/TimeoutRejectedException.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.Core/Timeout/TimeoutUtil.cs
  src/Polly.Core/Utils/ValidationHelper.cs
  src/Polly/Properties/AssemblyInfo.cs
  src/Polly/Timeout/TimeoutRejectedException.cs
  src/Polly/Timeout/TimeoutStrategy.cs
Labels: v8

#1085 Introduce ResilienceStrategyRegistry
  src/Polly.Core.Tests/Registry/ResilienceStrategyProviderTests.cs
  src/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  src/Polly.Core.Tests/Registry/StrategyId.cs
  src/Polly.Core/Registry/ResilienceStrategyProvider.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistryOptions.cs
Labels: v8
