Repository App-vNext/Polly, pull requests merged in 2023-07, with the labels that each got.

#1378 Exclude some labels from stale
  .github/workflows/stale.yml
Labels: github_actions

#1379 Debugger proxies for resilience strategies
  src/Polly.Core/ResilienceStrategy.DebuggerProxy.cs
  src/Polly.Core/ResilienceStrategy.TResult.Async.cs
  src/Polly.Core/ResilienceStrategy.TResult.DebuggerProxy.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Utils/ResilienceStrategyPipeline.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.cs
Labels: v8

#1383 Add support for `PartitionedRateLimiter`
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  src/Polly.RateLimiting/ResilienceRateLimiter.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  test/Polly.RateLimiting.Tests/ResilienceRateLimiterTests.cs
Labels: v8

#1384 Fix debugger proxies
  src/Polly.Core/ResilienceStrategy.DebuggerProxy.cs
  src/Polly.Core/ResilienceStrategy.TResult.Async.cs
  src/Polly.Core/ResilienceStrategy.TResult.DebuggerProxy.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Utils/ResilienceStrategyPipeline.DebuggerProxy.cs
  src/Polly.Core/Utils/ResilienceStrategyPipeline.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.cs
Labels: v8

#1386 Allow adding generic strategies to generic builder
  src/Polly.Core/ResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/GenericResilienceStrategyBuilderTests.cs
Labels: v8

#1385 Add new issue that demonstrates how to use PartitionedRateLimiter
  test/Polly.Extensions.Tests/Issues/IssuesTests.PartitionedRateLimiter_1365.cs
  test/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj
Labels: v8

#1387 Introduce `TelemetryOptions.OnTelemetryEvent`
  src/Polly.Core/Telemetry/ResilienceTelemetrySource.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryOptions.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
Labels: v8

#1388 `ResilienceStrategyRegistry` API improvements
  src/Polly.Core/Registry/ResilienceStrategyRegistry.TResult.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Registry/ConfigureBuilderContextExtensions.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
Labels: v8

#1391 Simplify condition
  .github/workflows/build.yml
Labels: enhancement, CI/build

#1392 Introduce `ResilienceStrategyBuilder.InstanceName` and use it in telemetry
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.TResult.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistryOptions.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Telemetry/ResilienceTelemetrySource.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryUtil.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryOptionsTests.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderContextTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1394 Introduce `Polly.Testing` package
  .github/workflows/build.yml
  Polly.sln
  build.cake
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Testing/InnerStrategiesDescriptor.cs
  src/Polly.Testing/Polly.Testing.csproj
  src/Polly.Testing/README.md
  src/Polly.Testing/ResilienceStrategyDescriptor.cs
  src/Polly.Testing/ResilienceStrategyExtensions.cs
  test/Polly.Testing.Tests/Polly.Testing.Tests.csproj
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8

#1395 Kill mutant
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
Labels: v8

#1396 Fix unstable test
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
Labels: v8

#1397 Rename AddResilienceStrategy to AddResilienceStrategyRegistry
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
Labels: v8

#1401 Update README.md for Polly.Extensions with telemetry info
  src/Polly.Core/README.md
  src/Polly.Extensions/README.md
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
Labels: v8

#1407 Kill mutant
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
Labels: v8

#1400 Include PublicApiAnalyzers
  Directory.Packages.props
  eng/Library.targets
  src/Polly.Core/CircuitBreaker/BrokenCircuitException.TResult.cs
  src/Polly.Core/CircuitBreaker/BrokenCircuitException.cs
  src/Polly.Core/CircuitBreaker/IsolatedCircuitException.cs
  src/Polly.Core/ExecutionRejectedException.cs
  src/Polly.Core/PublicAPI.Shipped.txt
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResilienceStrategy.Async.ValueTask.cs
  src/Polly.Core/ResilienceStrategy.Async.ValueTaskT.cs
  src/Polly.Core/ResilienceStrategy.Sync.cs
  src/Polly.Core/ResilienceStrategy.SyncT.cs
  src/Polly.Core/ResilienceStrategy.TResult.Async.cs
  src/Polly.Core/ResilienceStrategy.TResult.Sync.cs
  src/Polly.Core/Timeout/TimeoutRejectedException.cs
  src/Polly.Extensions/PublicAPI.Shipped.txt
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/PublicAPI.Shipped.txt
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/RateLimiterRejectedException.cs
  src/Polly.Testing/PublicAPI.Shipped.txt
  src/Polly.Testing/PublicAPI.Unshipped.txt
  src/Polly/Bulkhead/BulkheadRejectedException.cs
  src/Polly/Polly.csproj
  src/Polly/Properties/AssemblyInfo.cs
  src/Polly/PublicAPI.Shipped.txt
  src/Polly/PublicAPI.Unshipped.txt
  src/Polly/RateLimit/RateLimitRejectedException.cs
  test/Polly.TestUtils/Polly.TestUtils.csproj
Labels: v8

#1366 Demonstrate how to create dynamic strategies with complex keys
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
Labels: v8

#1412 Introduce ResilienceStrategyBuilder.Validator
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceValidationContext.cs
  src/Polly.Core/Utils/ValidationHelper.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutStrategyOptionsTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyBuilderExtensionsTests.cs
Labels: v8

#1413 Update docs.
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/SimpleCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/PredicateBuilder.TResult.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistryOptions.cs
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyOptions.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.Extensions/Telemetry/TelemetryOptions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
Labels: v8

#1414 Annotate the library with trimming attributes
  src/LegacySupport/DynamicDependencyAttribute.cs
  src/LegacySupport/DynamicallyAccessedMemberTypes.cs
  src/LegacySupport/DynamicallyAccessedMembersAttribute.cs
  src/LegacySupport/RequiresUnreferencedCodeAttribute.cs
  src/LegacySupport/UnconditionalSuppressMessageAttribute.cs
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Telemetry/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.Core/Utils/Constants.cs
  src/Polly.Core/Utils/ValidationHelper.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Registry/ConfigureBuilderContextExtensions.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Extensions/Utils/OptionsReloadHelper.cs
  src/Polly.RateLimiting/Polly.RateLimiting.csproj
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
Labels: v8

#1415 Update trimming justifications
  src/Polly.Core/Telemetry/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Utils/Constants.cs
  src/Polly.Core/Utils/ValidationHelper.cs
Labels: v8

#1416 Fix condition
  .github/workflows/build.yml
Labels: CI/build

#1420 API Review Feedback (1)
  bench/Polly.Core.Benchmarks/Utils/EmptyResilienceOptions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerConstants.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/Fallback/FallbackConstants.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Polly.Core/Hedging/HedgingConstants.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResilienceProperties.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/ResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/ResilienceStrategyOptions.cs
  src/Polly.Core/Retry/RetryConstants.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Retry/RetryStrategyOptions.cs
  src/Polly.Core/Telemetry/ResilienceTelemetrySource.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Core/Timeout/TimeoutConstants.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.Core/Utils/ReloadableResilienceStrategy.cs
  src/Polly.Extensions/README.md
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/RateLimiterConstants.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  test/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/ResilienceContextTests.cs
  test/Polly.Core.Tests/ResiliencePropertiesTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderContextTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/ResilienceStrategyOptionsTests.cs
  test/Polly.Core.Tests/Retry/RetryConstantsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutConstantsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutStrategyOptionsTests.cs
  test/Polly.Core.Tests/Utils/ReloadableResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Extensions.Tests/ReloadableResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterConstantsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterStrategyOptionsTests.cs
  test/Polly.TestUtils/TestResilienceStrategyOptions.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1422 Convert records to classes
  src/Polly.Core/CircuitBreaker/CircuitBreakerPredicateArguments.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/CircuitBreaker/OnCircuitClosedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitHalfOpenedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitOpenedArguments.cs
  src/Polly.Core/Fallback/FallbackPredicateArguments.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Fallback/OnFallbackArguments.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingDelayArguments.cs
  src/Polly.Core/Hedging/HedgingPredicateArguments.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Core/Retry/RetryDelayArguments.cs
  src/Polly.Core/Retry/RetryPredicateArguments.cs
  src/Polly.Core/Telemetry/ResilienceEvent.cs
  src/Polly.Core/Telemetry/ResilienceTelemetrySource.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.Pool.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.cs
  src/Polly.Core/Timeout/OnTimeoutArguments.cs
  src/Polly.Core/Timeout/TimeoutGeneratorArguments.cs
  src/Polly.RateLimiting/OnRateLimiterRejectedArguments.cs
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.Testing/InnerStrategiesDescriptor.cs
  src/Polly.Testing/PublicAPI.Unshipped.txt
  src/Polly.Testing/ResilienceStrategyDescriptor.cs
  src/Polly.Testing/ResilienceStrategyExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerPredicateArgumentsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/OnCircuitHalfOpenedArgumentsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackHandlerTests.cs
  test/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingPredicateArgumentsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Hedging/OnHedgingArgumentsTests.cs
  test/Polly.Core.Tests/PredicateBuilderTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceEventTests.cs
Labels: v8

#1424 Rename ExecuteCoreAsync to ExecuteCore
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/EmptyResilienceStrategy.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.CircuitBreaker.cs
  src/Polly.Core/NullResilienceStrategy.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/README.md
  src/Polly.Core/ResilienceStrategy.Async.ValueTask.cs
  src/Polly.Core/ResilienceStrategy.Async.ValueTaskT.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Utils/OutcomeResilienceStrategy.cs
  src/Polly.Core/Utils/ReloadableResilienceStrategy.cs
  src/Polly.Core/Utils/ResilienceStrategyPipeline.cs
  src/Polly.Core/Utils/TimeProviderExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Utils/ResilienceStrategyPipelineTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/ReloadableResilienceStrategyTests.cs
  test/Polly.TestUtils/TestResilienceStrategy.cs
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8

#1426 Benchmark for strategy creation
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CreationBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/CreationBenchmark.cs
Labels: v8

#1428 Improve usability of ResilienceStrategy<T>
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceStrategy.TResult.Async.cs
  src/Polly.Core/ResilienceStrategy.TResult.Sync.cs
Labels: v8

#1430 Cleanup OutcomeResilienceStrategy
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Utils/OutcomeResilienceStrategy.cs
  src/Polly.Core/Utils/TaskHelper.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/OutcomeResilienceStrategyTests.cs
Labels: v8

#1431 Drop the ResilienceStrategyBuilder.IsGenericBuilder property
  src/Polly.Core/Fallback/FallbackHandler.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/ResilienceStrategyBuilder.TResult.cs
  src/Polly.Core/ResilienceStrategyBuilder.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyBuilderContext.cs
  test/Polly.Core.Tests/Fallback/FallbackHandlerTests.cs
  test/Polly.Core.Tests/Fallback/FallbackHelper.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/GenericResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderContextTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
Labels: v8

#1432 Allow isolate CircuitBreakerManualControl using constructor
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerManualControlTests.cs
Labels: v8

#1436 Improve logging messages
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Extensions/Telemetry/TelemetryUtil.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Utils/TelemetryUtilTests.cs
Labels: v8

#1437 Rename `BuilderName` to `Name`
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/GenericResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
Labels: v8

#1438 Do not record null tags to meter
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
Labels: v8

#1439 Fix telemetry test failures
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1444 Drop simple circuit breaker
  bench/Polly.Core.Benchmarks/Utils/Helper.CircuitBreaker.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerConstants.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStateProvider.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/Controller/AdvancedCircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/Controller/ConsecutiveFailuresCircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/SimpleCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/SimpleCircuitBreakerStrategyOptions.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  test/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/AdvancedCircuitBehaviorTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/ConsecutiveFailuresCircuitBehaviorTests.cs
  test/Polly.Core.Tests/Issues/IssuesTests.CircuitBreakerStateSharing_959.cs
  test/Polly.Core.Tests/PredicateBuilderTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8

#1445 Allow jitter for all backoff types
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/RetryBackoffType.cs
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
Labels: v8

#1447 Rename `Attempt` to `AttemptNumber`
  src/Polly.Core/Hedging/Controller/HedgingHandler.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingDelayArguments.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Core/Retry/RetryDelayArguments.cs
  src/Polly.Core/Retry/RetryPredicateArguments.cs
  src/Polly.Core/Telemetry/ExecutionAttemptArguments.Pool.cs
  src/Polly.Core/Telemetry/ExecutionAttemptArguments.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActionGeneratorArgumentsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActions.cs
  test/Polly.Core.Tests/Hedging/HedgingDelayArgumentsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/OnHedgingArgumentsTests.cs
  test/Polly.Core.Tests/Retry/OnRetryArgumentsTests.cs
  test/Polly.Core.Tests/Retry/RetryDelayArgumentsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/ShouldRetryArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/ExecutionAttemptArgumentsTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1448 Rename `ResilienceStrategyBuilder` to `CompositeStrategyBuilder`
  bench/Polly.Core.Benchmarks/CreationBenchmark.cs
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.CircuitBreaker.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStateProvider.cs
  src/Polly.Core/CompositeStrategyBuilder.TResult.cs
  src/Polly.Core/CompositeStrategyBuilder.cs
  src/Polly.Core/CompositeStrategyBuilderBase.cs
  src/Polly.Core/CompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/README.md
  src/Polly.Core/Registry/ResilienceStrategyRegistry.TResult.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistryOptions.cs
  src/Polly.Core/Retry/RetryCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/StrategyBuilderContext.cs
  src/Polly.Core/Timeout/TimeoutCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Utils/CompositeResilienceStrategy.cs
  src/Polly.Core/Utils/ResilienceStrategyPipeline.DebuggerProxy.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.Extensions/README.md
  src/Polly.Extensions/Telemetry/TelemetryCompositeStrategyBuilderExtensions.cs
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/RateLimiterCompositeStrategyBuilderExtensions.cs
  src/Polly.Testing/README.md
  src/Polly.Testing/ResilienceStrategyExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerCompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/CompositeStrategyBuilderContextTests.cs
  test/Polly.Core.Tests/CompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/Fallback/FallbackCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/GenericCompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/Hedging/HedgingCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Issues/IssuesTests.CircuitBreakerStateSharing_959.cs
  test/Polly.Core.Tests/Issues/IssuesTests.FlowingContext_849.cs
  test/Polly.Core.Tests/Issues/IssuesTests.HandleMultipleResults_898.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Utils/CompositeResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  test/Polly.Specs/ResilienceStrategyConversionExtensionsTests.cs
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8
