Repository App-vNext/Polly, pull requests merged in 2023-10, with the labels that each got.

#1669 Enable search for docs
  docs/docfx.json
Labels: enhancement, documentation

#1673 Docs: Include info about numerical type used in metrics in telemetry.md
  docs/advanced/telemetry.md
Labels: documentation

#1675 [Docs] Expand fault handling docs
  README.md
  docs/index.md
  docs/strategies/index.md
  src/Snippets/Docs/ResilienceStrategies.cs
Labels: documentation

#1667 Add spell checker
  .github/spellcheck.yml
  .github/wordlist.txt
  .github/workflows/gh-pages.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  docs/advanced/simmy.md
  docs/api/index.md
  docs/community/libraries-and-contributions.md
  docs/community/polly-contrib.md
  docs/community/resources.md
  docs/index.md
  docs/migration-v8.md
  docs/strategies/circuit-breaker.md
  docs/strategies/retry.md
  docs/v7/extensibility.md
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Snippets/README.md
Labels: enhancement, documentation, CI/build, dependencies, github_actions

#1681 [Docs] Improve telemetry docs
  docs/advanced/resilience-context.md
  docs/advanced/telemetry.md
  src/Snippets/Docs/Telemetry.cs
Labels: documentation

#1684 [Docs] Improve registry docs
  docs/pipelines/resilience-pipeline-registry.md
Labels: documentation

#1685 [Docs] Fix link to ResiliencePipelineBuilder
  docs/pipelines/resilience-pipeline-registry.md
Labels: documentation

#1676 Use GitHub Issue template forms
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/10_bug_report.yml
  .github/ISSUE_TEMPLATE/20_feature_request.yml
  .github/ISSUE_TEMPLATE/30_question.yml
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/how-to.md
  .github/ISSUE_TEMPLATE/request.md
  .github/wordlist.txt
  CONTRIBUTING.md
  README.md
  build.ps1
  docs/community/git-workflow.md
  docs/community/libraries-and-contributions.md
  docs/community/polly-contrib.md
  docs/community/resources.md
  docs/index.md
  docs/toc.yml
  docs/v7/extensibility.md
  src/Polly/Utilities/TimedLock.cs
  test/Polly.Specs/Retry/RetryAsyncSpecs.cs
  test/Polly.Specs/Retry/RetryForeverAsyncSpecs.cs
  test/Polly.Specs/Retry/RetryTResultSpecsAsync.cs
  test/Polly.Specs/Retry/WaitAndRetryAsyncSpecs.cs
  test/Polly.Specs/Retry/WaitAndRetryForeverAsyncSpecs.cs
Labels: documentation

#1698 [Docs] Fallback after retries
  docs/migration-v8.md
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/retry.md
  src/Snippets/Docs/Fallback.cs
  src/Snippets/Docs/Retry.cs
Labels: documentation

#1699 [Docs] Add sequence diagrams to timeout strategy
  docs/media/timeout strategy happy path.png
  docs/media/timeout strategy unhappy path.png
  docs/strategies/timeout.md
Labels: documentation

#1697 Update to cancel downstream operation in TimeoutStrategy.Pessimistic
  src/Polly/Timeout/AsyncTimeoutEngine.cs
  test/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
Labels: bug fix

#1704 [Docs] Add diagrams to circuit breaker
  docs/strategies/circuit-breaker.md
  docs/strategies/rate-limiter.md
Labels: documentation

#1705 [Docs] Remove theme overwrites from mermaid diagrams
  .config/dotnet-tools.json
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/rate-limiter.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
Labels: documentation

#1707 Add link to retries blog
  docs/community/resources.md
Labels: documentation

#1706 [Docs] Add sequence diagrams to hedging
  docs/strategies/hedging.md
Labels: documentation

#1712 [Docs] Improvements
  docs/advanced/telemetry.md
  src/Snippets/Docs/Telemetry.cs
Labels: documentation

#1714 [Docs] Add diagrams to resilience pipeline
  docs/pipelines/index.md
  src/Snippets/Docs/ResiliencePipelines.cs
Labels: documentation

#1713 [Docs] Add diagram to action generator hedging
  docs/strategies/circuit-breaker.md
  docs/strategies/fallback.md
  docs/strategies/hedging.md
  docs/strategies/rate-limiter.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
  src/Snippets/Docs/Hedging.cs
Labels: documentation

#1722 [Docs] Update DocFx
  .config/dotnet-tools.json
Labels: documentation, dependencies

#1724 [Docs] Add docs for metering enrichment
  .github/wordlist.txt
  docs/advanced/telemetry.md
  src/Snippets/Docs/Telemetry.cs
Labels: documentation

#1725 [Docs] Fix the API generation
  docs/docfx.json
Labels: documentation, bug fix

#1726 [Docs] Add sequence diagram to resilience context
  docs/advanced/resilience-context.md
Labels: documentation

#1730 [Docs] Fix hedging documentation about unhappy paths
  .github/workflows/gh-pages.yml
  docs/strategies/hedging.md
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
Labels: documentation

#1733 [Docs] Minor fixes on pipeline registry
  docs/pipelines/resilience-pipeline-registry.md
  src/Snippets/Docs/ResiliencePipelineRegistry.cs
Labels: documentation

#1739 Update NuGet tools
  build.cake
Labels: CI/build, dependencies, .NET

#1746 Bump docfx
  .config/dotnet-tools.json
Labels: documentation, dependencies

#1744 Resolve IL2091 warnings
  src/Polly.Core/Simmy/Outcomes/OutcomePipelineBuilderExtensions.cs
Labels: bug fix, aot

#1747 Prevent concurrent page builds
  .github/workflows/gh-pages.yml
Labels: documentation, bug fix, github_actions

#1748 Fix test
  test/Polly.Specs/Caching/AbsoluteTtlSpecs.cs
Labels: bug

#1750 Restore 100% mutations
  src/Polly.Core/Polly.Core.csproj
  test/Polly.Core.Tests/ResiliencePipelineTests.cs
Labels: CI/build

#1728 [Docs] Fix the policywrap sample
  docs/migration-v8.md
  src/Snippets/Docs/Migration.Wrap.cs
Labels: documentation

#1749 [Docs] Hedging context
  docs/strategies/hedging.md
Labels: documentation

#1752 Run mutation tests on Windows instead of Linux
  .github/workflows/build.yml
Labels: CI/build

#1753 Speed-up page builds
  .github/workflows/gh-pages.yml
Labels: CI/build

#1751 [Docs] Add diagram about hedging's context and callbacks
  docs/strategies/hedging.md
Labels: documentation

#1737 Resolve AOT compilation issues
  CHANGELOG.md
  Polly.sln
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CompositeComponentBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.DelegatingComponentBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/DelegatingComponentBenchmark.cs
  build.cake
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Core/Utils/Pipeline/CompositeComponent.cs
  src/Polly.Core/Utils/Pipeline/DelegatingComponent.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponent.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.RateLimiting/Polly.RateLimiting.csproj
  test/Polly.AotTest/Polly.AotTest.csproj
  test/Polly.AotTest/Program.cs
  test/Polly.Core.Tests/Utils/Pipeline/DelegatingComponentTests.cs
Labels: bug fix, aot

#1763 [Docs] Add minor tweaks to migration guide 1/3
  docs/migration-v8.md
  src/Snippets/Docs/Migration.Bulkhead.cs
  src/Snippets/Docs/Migration.Policies.cs
  src/Snippets/Docs/Migration.Retry.cs
Labels: documentation

#1761 Fix package signing verification
  .github/workflows/build.yml
Labels: CI/build, bug fix, dependencies, github_actions
