Repository App-vNext/Polly, pull requests merged in 2023-04, with the labels that each got.

#1094 Introduce base class for predicates
  src/Polly.Core.Tests/Polly.Core.Tests.csproj
  src/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  src/Polly.Core.Tests/Retry/ShouldRetryArgumentsTests.cs
  src/Polly.Core.Tests/Strategy/OutcomePredicateTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeTests.cs
  src/Polly.Core/Retry/RetryStrategyOptions.cs
  src/Polly.Core/Retry/ShouldRetryArguments.cs
  src/Polly.Core/Retry/ShouldRetryPredicate.cs
  src/Polly.Core/Strategy/Outcome.cs
  src/Polly.Core/Strategy/OutcomePredicate.Handler.cs
  src/Polly.Core/Strategy/OutcomePredicate.cs
Labels: v8

#1088 Introduce Polly.Extensions project
  .github/dependabot.yml
  build.cake
  eng/Common.targets
  src/Directory.Packages.props
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderOptionsTests.cs
  src/Polly.Core.Tests/Utils/TimeProviderExtensionsTests.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilderOptions.cs
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Extensions.Tests/DependencyInjection/PollyDependencyInjectionKeysTests.cs
  src/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  src/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/DependencyInjection/ConfigureResilienceStrategyRegistryOptions.cs
  src/Polly.Extensions/DependencyInjection/PollyDependencyInjectionKeys.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/README.md
  src/Polly.sln
  src/Polly/Polly.csproj
Labels: v8

#1095 Introduce OutcomeGenerator
  src/Polly.Core.Tests/Polly.Core.Tests.csproj
  src/Polly.Core.Tests/Retry/RetryDelayArgumentsTests.cs
  src/Polly.Core.Tests/Retry/RetryDelayGeneratorTests.cs
  src/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeGeneratorTests.cs
  src/Polly.Core/Retry/RetryDelayArguments.cs
  src/Polly.Core/Retry/RetryDelayGenerator.cs
  src/Polly.Core/Retry/RetryStrategyOptions.cs
  src/Polly.Core/Strategy/OutcomeGenerator.Handler.cs
  src/Polly.Core/Strategy/OutcomeGenerator.cs
Labels: v8

#1096 Introduce OutcomeEvent
  src/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  src/Polly.Core.Tests/Strategy/OnRetryArgumentsTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeEventTests.cs
  src/Polly.Core.Tests/Strategy/SimpleEventTests.cs
  src/Polly.Core.Tests/Timeout/OnTimeoutEventTests.cs
  src/Polly.Core.Tests/Utils/TestArguments.cs
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Core/Retry/OnRetryEvent.cs
  src/Polly.Core/Retry/RetryStrategyOptions.cs
  src/Polly.Core/Strategy/OutcomeEvent.Handler.cs
  src/Polly.Core/Strategy/OutcomeEvent.cs
  src/Polly.Core/Strategy/SimpleEvent.cs
  src/Polly.Core/Timeout/OnTimeoutEvent.cs
Labels: v8

#1099 Update README.md
  .vscode/extensions.json
  README.md
Labels: enhancement, documentation

#1101 Introduce RetryResilienceStrategy
  src/Polly.Core.Tests/Retry/RetryConstantsTests.cs
  src/Polly.Core.Tests/Retry/RetryDelayArgumentsTests.cs
  src/Polly.Core.Tests/Retry/RetryDelayGeneratorTests.cs
  src/Polly.Core.Tests/Retry/RetryHelperTests.cs
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  src/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  src/Polly.Core.Tests/Strategy/OnRetryArgumentsTests.cs
  src/Polly.Core.Tests/Strategy/SimpleEventTests.cs
  src/Polly.Core.Tests/Telemetry/NullResilienceTelemetryTests.cs
  src/Polly.Core.Tests/Utils/FakeTimeProvider.cs
  src/Polly.Core.Tests/Utils/TimeSpanAttributeTests.cs
  src/Polly.Core.Tests/Utils/ValidationContextExtensions.cs
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Core/Retry/RetryBackoffType.cs
  src/Polly.Core/Retry/RetryConstants.cs
  src/Polly.Core/Retry/RetryDelayArguments.cs
  src/Polly.Core/Retry/RetryDelayGenerator.cs
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryStrategyOptions.cs
  src/Polly.Core/Strategy/SimpleEvent.cs
  src/Polly.Core/Telemetry/NullResilienceTelemetry.cs
  src/Polly.Core/Telemetry/ResilienceTelemetry.cs
  src/Polly.Core/Timeout/OnTimeoutEvent.cs
  src/Polly.Core/Utils/TimeSpanAttribute.cs
  src/Polly.Core/Utils/ValidationContextExtensions.cs
Labels: v8

#1103 Introduce RateLimiterResilienceStrategy
  .github/dependabot.yml
  .github/workflows/build.yml
  build.cake
  src/Directory.Packages.props
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Strategy/SimpleEvent.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Utils/Guard.cs
  src/Polly.Core/Utils/SynchronousExecutionHelper.cs
  src/Polly.Core/Utils/ValidationHelper.cs
  src/Polly.RateLimiting.Tests/OnRateLimiterRejectedArgumentsTests.cs
  src/Polly.RateLimiting.Tests/OnRateLimiterRejectedEventTests.cs
  src/Polly.RateLimiting.Tests/Polly.RateLimiting.Tests.csproj
  src/Polly.RateLimiting.Tests/RateLimiterConstantsTests.cs
  src/Polly.RateLimiting.Tests/RateLimiterRejectedExceptionTests.cs
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  src/Polly.RateLimiting.Tests/RateLimiterStrategyOptionsTests.cs
  src/Polly.RateLimiting/OnRateLimiterRejectedArguments.cs
  src/Polly.RateLimiting/OnRateLimiterRejectedEvent.cs
  src/Polly.RateLimiting/Polly.RateLimiting.csproj
  src/Polly.RateLimiting/README.md
  src/Polly.RateLimiting/RateLimiterConstants.cs
  src/Polly.RateLimiting/RateLimiterRejectedException.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  src/Polly.sln
Labels: v8

#1107 Cleanup rate limiter extensions
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.RateLimiting/README.md
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
Labels: v8

#1106 Add more benchmarks for V8
  src/Polly.Core.Benchmarks/Benchmarks/RateLimiterBenchmark.cs
  src/Polly.Core.Benchmarks/Benchmarks/RetryBenchmark.cs
  src/Polly.Core.Benchmarks/Benchmarks/StrategyPipelineBenchmark.cs
  src/Polly.Core.Benchmarks/Benchmarks/TimeoutBenchmark.cs
  src/Polly.Core.Benchmarks/Internals/Helper.Pipeline.cs
  src/Polly.Core.Benchmarks/Internals/Helper.RateLimiting.cs
  src/Polly.Core.Benchmarks/Internals/Helper.Retry.cs
  src/Polly.Core.Benchmarks/Internals/Helper.StrategyPipeline.cs
  src/Polly.Core.Benchmarks/Internals/Helper.Timeout.cs
  src/Polly.Core.Benchmarks/Polly.Core.Benchmarks.csproj
  src/Polly.Core.Benchmarks/README.md
Labels: v8

#1105 Update LICENSE file
  LICENSE
  LICENSE.txt
Labels: documentation

#1104 Add OSSF Scorecard
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/ossf-scorecard.yml
  .github/workflows/update-dotnet-sdk.yml
  SECURITY.md
Labels: enhancement, CI/build

#1115 Fix unstable tests
  build.cake
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.Task.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.TaskT.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.ValueTask.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.ValueTaskT.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Sync.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.SyncT.cs
  src/Polly.Core.Tests/Utils/TimeProviderExtensionsTests.cs
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
Labels: v8

#1124 Minor API cleanup
  src/Polly.Core.Tests/Builder/ResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.Task.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.Async.TaskT.cs
  src/Polly.Core.Tests/Strategy/ResilienceStrategyOptionsTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  src/Polly.Core/Builder/ResilienceStrategyBuilder.cs
  src/Polly.Core/ResilienceStrategy.Async.Task.cs
  src/Polly.Core/ResilienceStrategy.Async.TaskT.cs
  src/Polly.Core/Retry/RetryStrategyOptions.cs
  src/Polly.Core/Strategy/ResilienceStrategyOptions.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
Labels: v8

#1128 Add Async suffix to some APIs
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeEventTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeGeneratorTests.cs
  src/Polly.Core.Tests/Strategy/OutcomePredicateTests.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Strategy/OutcomeEvent.Handler.cs
  src/Polly.Core/Strategy/OutcomeGenerator.Handler.cs
  src/Polly.Core/Strategy/OutcomePredicate.Handler.cs
Labels: v8

#1135 Recommend GitHub Actions extension
  .vscode/extensions.json
Labels: enhancement

#1136 Cleanup the namespaces
  src/Polly.Core.Benchmarks/Internals/Helper.cs
  src/Polly.Core.Tests/Helpers/TestUtils.cs
  src/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  src/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  src/Polly.Core.Tests/Strategy/ResilienceStrategyBuilderContextTests.cs
  src/Polly.Core.Tests/Strategy/ResilienceStrategyPipelineTests.cs
  src/Polly.Core.Tests/Strategy/ResilienceStrategyTelemetryTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistryOptions.cs
  src/Polly.Core/ResilienceStrategyBuilder.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Strategy/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Strategy/ResilienceStrategyPipeline.cs
  src/Polly.Core/Strategy/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
Labels: v8

#1137 Finalize the callback API
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Retry/RetryStrategyOptionsTResultTests.cs
  src/Polly.Core.Tests/Strategy/NoOutcomeGeneratorTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeEventTests.cs
  src/Polly.Core.Tests/Strategy/OutcomeGeneratorTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutGeneratorTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Strategy/NoOutcomeGenerator.cs
  src/Polly.Core/Strategy/OutcomeEvent.Handler.cs
  src/Polly.Core/Strategy/OutcomeEvent.TResult.cs
  src/Polly.Core/Strategy/OutcomeEvent.cs
  src/Polly.Core/Strategy/OutcomeGenerator.Handler.cs
  src/Polly.Core/Strategy/OutcomeGenerator.TResult.cs
  src/Polly.Core/Strategy/OutcomeGenerator.cs
  src/Polly.Core/Strategy/OutcomePredicate.cs
  src/Polly.Core/Timeout/TimeoutGenerator.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
Labels: v8

#1138 Resilience telemetry API
  .editorconfig
  .github/dependabot.yml
  src/Directory.Packages.props
  src/Polly.Core.Tests/Registry/ResilienceStrategyRegistryOptionsTests.cs
  src/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  src/Polly.Core.Tests/ResilienceContextTests.cs
  src/Polly.Core.Tests/Strategy/ResilienceStrategyTelemetryTests.cs
  src/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistryOptions.cs
  src/Polly.Core/Strategy/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  src/Polly.Extensions.Tests/Helpers/FakeLogger.cs
  src/Polly.Extensions.Tests/Helpers/TestArguments.cs
  src/Polly.Extensions.Tests/Helpers/TestStrategy.cs
  src/Polly.Extensions.Tests/Helpers/TestUtils.cs
  src/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj
  src/Polly.Extensions.Tests/Telemetry/EnrichmentContextTests.cs
  src/Polly.Extensions.Tests/Telemetry/ResilienceStrategyTelemetryOptionsTests.cs
  src/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  src/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Telemetry/EnrichmentContext.Pool.cs
  src/Polly.Extensions/Telemetry/EnrichmentContext.cs
  src/Polly.Extensions/Telemetry/ResilienceStrategyTelemetryOptions.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
Labels: v8

#1145 Introduce API for Circuit Breaker Strategy
  src/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/BrokenCircuitExceptionTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerManualControlTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerOptionsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerPredicateArgumentsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerStateProviderTests.cs
  src/Polly.Core.Tests/CircuitBreaker/IsolatedCircuitExceptionTests.cs
  src/Polly.Core.Tests/CircuitBreaker/OnCircuitClosedArgumentsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/OnCircuitHalfOpenedArgumentsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/OnCircuitOpenedArgumentsTests.cs
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/BaseCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/BaseCircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/BrokenCircuitException.TResult.cs
  src/Polly.Core/CircuitBreaker/BrokenCircuitException.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerConstants.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerPredicateArguments.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStateProvider.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/CircuitState.cs
  src/Polly.Core/CircuitBreaker/IsolatedCircuitException.cs
  src/Polly.Core/CircuitBreaker/OnCircuitClosedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitHalfOpenedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitOpenedArguments.cs
  src/Polly.Core/Strategy/NoOutcomeEvent.cs
  src/Polly/CircuitBreaker/BrokenCircuitException.cs
  src/Polly/CircuitBreaker/CircuitState.cs
  src/Polly/CircuitBreaker/IsolatedCircuitException.cs
  src/Polly/Properties/AssemblyInfo.cs
Labels: v8

#1151 Run mutations tests on linux only
  .github/workflows/build.yml
  build.cake
Labels: CI/build, v8

#1152 Migrate `CircuitStateController` and implement `CircutBreakerResilienceStrategy `
  build.cake
  src/Directory.Packages.props
  src/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerManualControlTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerOptionsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  src/Polly.Core.Tests/CircuitBreaker/CircuitBreakerStateProviderTests.cs
  src/Polly.Core.Tests/CircuitBreaker/Controller/AdvancedCircuitBehaviorTests.cs
  src/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  src/Polly.Core.Tests/CircuitBreaker/Controller/ConsecutiveFailuresCircuitBehaviorTests.cs
  src/Polly.Core.Tests/CircuitBreaker/Controller/ScheduledTaskExecutorTests.cs
  src/Polly.Core.Tests/CircuitBreaker/OnCircuitClosedArgumentsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/OnCircuitOpenedArgumentsTests.cs
  src/Polly.Core/CircuitBreaker/BaseCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/BaseCircuitBreakerStrategyOptions.cs
  src/Polly.Core/CircuitBreaker/BrokenCircuitException.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerConstants.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStateProvider.cs
  src/Polly.Core/CircuitBreaker/Controller/AdvancedCircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/CircuitBreaker/Controller/ConsecutiveFailuresCircuitBehavior.cs
  src/Polly.Core/CircuitBreaker/Controller/ScheduledTaskExecutor.cs
  src/Polly.Core/CircuitBreaker/OnCircuitClosedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitOpenedArguments.cs
  src/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1158 Introduce Fallback Resilience Strategy
  src/Polly.Core.Benchmarks/Internals/Helper.Pipeline.cs
  src/Polly.Core.Tests/Fallback/FallbackHandlerTests.cs
  src/Polly.Core.Tests/Fallback/FallbackResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  src/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTResultTests.cs
  src/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTests.cs
  src/Polly.Core/Fallback/FallbackConstants.cs
  src/Polly.Core/Fallback/FallbackHandler.Handler.cs
  src/Polly.Core/Fallback/FallbackHandler.TResult.cs
  src/Polly.Core/Fallback/FallbackHandler.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.cs
  src/Polly.Core/Fallback/HandleFallbackArguments.cs
  src/Polly.Core/Fallback/OnFallbackArguments.cs
  src/Polly.Core/Fallback/VoidFallbackHandler.cs
Labels: v8

#1159 Update the callback API docs
  build.cake
  src/Polly.Core/README.md
Labels: v8

#1161 Implement HedgingResilienceStrategy
  .github/dependabot.yml
  src/Directory.Packages.props
  src/Polly.Core.Benchmarks/Benchmarks/HedgingBenchmark.cs
  src/Polly.Core.Benchmarks/Internals/Helper.Hedging.cs
  src/Polly.Core.Benchmarks/README.md
  src/Polly.Core.Tests/Hedging/Controller/HedgingControllerTests.cs
  src/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  src/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  src/Polly.Core.Tests/Hedging/HedgingActionGeneratorArgumentsTests.cs
  src/Polly.Core.Tests/Hedging/HedgingActions.cs
  src/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  src/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  src/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTResultTests.cs
  src/Polly.Core.Tests/Hedging/HedgingTimeProvider.cs
  src/Polly.Core.Tests/Hedging/PrimaryStringTasks.cs
  src/Polly.Core.Tests/Helpers/DisposableResult.cs
  src/Polly.Core.Tests/ResilienceContextTests.cs
  src/Polly.Core.Tests/ResiliencePropertiesTests.cs
  src/Polly.Core.Tests/Utils/DisposeHelperTests.cs
  src/Polly.Core/Hedging/Controller/ContextSnapshot.cs
  src/Polly.Core/Hedging/Controller/HedgedTaskType.cs
  src/Polly.Core/Hedging/Controller/HedgingController.cs
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.TResult.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingConstants.cs
  src/Polly.Core/Hedging/HedgingHandler.Handler.cs
  src/Polly.Core/Hedging/HedgingHandler.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResilienceProperties.cs
  src/Polly.Core/Strategy/Outcome.cs
  src/Polly.Core/Utils/DisposeHelper.cs
  src/Polly.Core/Utils/IObjectPool.cs
  src/Polly.Core/Utils/ObjectPool.cs
Labels: v8
