Repository App-vNext/Polly, pull requests merged in 2023-06, with the labels that each got.

#1243 Introduce Outcome.EnsureSuccess
  src/Polly.Core.Tests/Strategy/OutcomeTests.cs
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/Strategy/Outcome.cs
  src/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
Labels: v8

#1239 API review feedback
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  src/Polly.Core/Strategy/Outcome.cs
  src/Polly.Core/Strategy/PredicateBuilder.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
Labels: v8

#1252 Update the benchmarks
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerOpenedBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.GenericOverheadBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.HedgingBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PipelineBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RateLimiterBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResilienceStrategyBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResilienceStrategyProviderBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RetryBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TimeoutBenchmark-report-github.md
Labels: v8

#1253 Add TelemetryBenchmark
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TelemetryBenchmark-report-github.md
  src/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
Labels: v8

#1255 Bridge between Polly V7 and Polly V8
  src/Polly.Specs/Polly.Specs.csproj
  src/Polly.Specs/ResilienceStrategyConversionExtensionsTests.cs
  src/Polly/Context.cs
  src/Polly/ResilienceStrategyConversionExtensions.cs
  src/Polly/Utilities/Wrappers/ResilienceContextFactory.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategyAsyncPolicy.TResult.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategyAsyncPolicy.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategySyncPolicy.TResult.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategySyncPolicy.cs
Labels: v8

#1257 Improve the V8 -> V7 bridge implementation and add benchmarks
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.BridgeBenchmark-report-github.md
  src/Polly.Core.Benchmarks/BridgeBenchmark.cs
  src/Polly.Core.Tests/Utils/LegacySupportTests.cs
  src/Polly.Core/ResilienceProperties.cs
  src/Polly.Core/Utils/LegacySupport.cs
  src/Polly.Specs/ResilienceStrategyConversionExtensionsTests.cs
  src/Polly/Utilities/Wrappers/ResilienceContextFactory.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategyAsyncPolicy.TResult.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategyAsyncPolicy.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategySyncPolicy.TResult.cs
  src/Polly/Utilities/Wrappers/ResilienceStrategySyncPolicy.cs
Labels: v8

#1251 The `BuilderName` and `StrategyName` now defaults to null
  src/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  src/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  src/Polly.Core.Tests/GenericResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  src/Polly.Core.Tests/Strategy/ResilienceStrategyOptionsTests.cs
  src/Polly.Core/Strategy/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/Strategy/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Strategy/ResilienceStrategyOptions.cs
  src/Polly.Core/Telemetry/ResilienceTelemetrySource.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
Labels: v8

#1254 Enable dynamic reloads
  src/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  src/Polly.Core.Tests/Utils/ReloadableResilienceStrategyTests.cs
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/Utils/ReloadableResilienceStrategy.cs
Labels: v8

#1261 Simplify implementation of synchronous execute methods
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResilienceStrategyBenchmark-report-github.md
  src/Polly.Core.Benchmarks/ResilienceStrategyBenchmark.cs
  src/Polly.Core/ResilienceStrategy.Sync.cs
  src/Polly.Core/ResilienceStrategy.SyncT.cs
  src/Polly.Core/ResilienceStrategy.cs
Labels: v8

#1262 Speed-up and drop allocations in ResilienceStrategyRegistry
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResilienceStrategyProviderBenchmark-report-github.md
  src/Polly.Core/Registry/ResilienceStrategyRegistry.TResult.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
Labels: v8

#1134 Add publish workflow
  .github/workflows/build.yml
  build.cake
Labels: CI/build, v8, github_actions

#1271 Add NuGet package README
  eng/Common.targets
  eng/Library.targets
Labels: enhancement, CI/build, v8

#1269 Add package signing
  .github/workflows/build.yml
  eng/signing/filelist.txt
Labels: CI/build, v8

#1276 Drop allocations when using ResilienceProperties
  src/Polly.Core.Tests/ResiliencePropertiesTests.cs
  src/Polly.Core/ResilienceProperties.cs
Labels: v8

#1264 Cleanup hedging internals
  src/Polly.Core.Tests/Hedging/Controller/HedgingControllerTests.cs
  src/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  src/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  src/Polly.Core.Tests/Hedging/HedgingActionGeneratorArgumentsTests.cs
  src/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  src/Polly.Core.Tests/Hedging/HedgingHelper.cs
  src/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  src/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTResultTests.cs
  src/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  src/Polly.Core/Hedging/Controller/HedgingController.cs
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Core/Hedging/Controller/HedgingHandler.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.TResult.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingHandler.Handler.cs
  src/Polly.Core/Hedging/HedgingHandler.TResult.cs
  src/Polly.Core/Hedging/HedgingHandler.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.cs
  src/Polly.Core/Hedging/VoidHedgingHandler.cs
Labels: v8

#1277 Safer execution of resilience strategies
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PipelineBenchmark-report-github.md
  src/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  src/Polly.Core.Tests/ResilienceStrategyTests.cs
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  src/Polly.Core.Tests/Utils/ResilienceStrategyPipelineTests.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Utils/ResilienceStrategyPipeline.cs
Labels: v8

#1278 Cleanup fallback internals
  src/Polly.Core.Tests/Fallback/FallbackHandlerTests.cs
  src/Polly.Core.Tests/Fallback/FallbackHelper.cs
  src/Polly.Core.Tests/Fallback/FallbackResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  src/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTResultTests.cs
  src/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTests.cs
  src/Polly.Core/Fallback/FallbackHandler.Handler.cs
  src/Polly.Core/Fallback/FallbackHandler.TResult.cs
  src/Polly.Core/Fallback/FallbackHandler.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.cs
  src/Polly.Core/Fallback/VoidFallbackHandler.cs
Labels: v8

#1279 Allow listening for options changes
  src/Directory.Packages.props
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj
  src/Polly.Extensions.Tests/ReloadableResilienceStrategyTests.cs
  src/Polly.Extensions.Tests/Telemetry/EnrichmentContextTests.cs
  src/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  src/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  src/Polly.Extensions.Tests/Utils/OptionsReloadHelperTests.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Extensions/Utils/OptionsReloadHelper.cs
  src/Polly.Extensions/Utils/OptionsReloadHelperRegistry.cs
Labels: v8

#1275 Use MinVer for versioning
  .config/dotnet-tools.json
  .github/workflows/build.yml
  GitVersion.yml
  README.md
  Version.props
  build.cake
  eng/Benchmark.targets
  eng/Library.targets
  src/Directory.Packages.props
Labels: enhancement, CI/build, bug fix, v8

#1283 Drop some convienience extensions
  src/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
Labels: v8

#1282 Update the benchmarks
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.BridgeBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerOpenedBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.GenericOverheadBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.HedgingBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PipelineBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RateLimiterBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResilienceStrategyBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResilienceStrategyProviderBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RetryBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TelemetryBenchmark-report-github.md
  BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TimeoutBenchmark-report-github.md
Labels: v8

#1285 Add remarks about binary compatibility to all structs
  src/Polly.Core/CircuitBreaker/CircuitBreakerPredicateArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitClosedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitHalfOpenedArguments.cs
  src/Polly.Core/CircuitBreaker/OnCircuitOpenedArguments.cs
  src/Polly.Core/Fallback/HandleFallbackArguments.cs
  src/Polly.Core/Fallback/OnFallbackArguments.cs
  src/Polly.Core/Hedging/HandleHedgingArguments.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingDelayArguments.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  src/Polly.Core/Outcome.cs
  src/Polly.Core/OutcomeArguments.cs
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Core/Retry/RetryDelayArguments.cs
  src/Polly.Core/Retry/ShouldRetryArguments.cs
  src/Polly.Core/Telemetry/ResilienceEvent.cs
  src/Polly.Core/Timeout/OnTimeoutArguments.cs
  src/Polly.RateLimiting/OnRateLimiterRejectedArguments.cs
Labels: v8

#1288 Rename package icon
  eng/Library.targets
  package-icon.png
Labels: CI/build, v8

#1284 Update CHANGELOG
  CHANGELOG.md
  src/Polly.Benchmarks/PollyConfig.cs
Labels: documentation

#1292 Update NuGet badge
  README.md
Labels: v8

#1294 Introduce `TelemetryResilienceStrategyOptions.ResultFormatter`
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyOptions.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyOptionsTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
Labels: v8

#1296 Add v8 alpha.1 changelog and fix-up package README
  CHANGELOG.md
  eng/Library.targets
  package-readme.md
Labels: documentation, CI/build, bug fix, v8

#1298 Cleanup Polly.Core README.md
  src/Polly.Core/README.md
Labels: v8

#1299 Drop redundant validation of resilience strategy options
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Utils/TypeNameFormatter.cs
  src/Polly.RateLimiting/Polly.RateLimiting.csproj
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Utils/TypeNameFormatterTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
Labels: v8

#1305 Add NuGet configuration file
  NuGet.config
Labels: CI/build, v8

#1306 Log unhealthy executions with warning level
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceContextExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.TestUtils/FakeLogger.cs
  test/Polly.TestUtils/LogRecord.cs
Labels: v8

#1307 Add hedging to package tags
  eng/Library.targets
Labels: v8

#1295 Introduce `samples` folder
  CHANGELOG.md
  Directory.Packages.props
  samples/.vscode/settings.json
  samples/DependencyInjection/DependencyInjection.csproj
  samples/DependencyInjection/Program.cs
  samples/Directory.Build.props
  samples/Directory.Build.targets
  samples/Extensibility/Extensibility.csproj
  samples/Extensibility/Program.cs
  samples/GenericStrategies/GenericStrategies.csproj
  samples/GenericStrategies/Program.cs
  samples/Intro/Intro.csproj
  samples/Intro/Program.cs
  samples/README.md
  samples/Retries/Program.cs
  samples/Retries/Retries.csproj
  samples/Samples.sln
Labels: v8

#1311 Update telemetry benchmark
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TelemetryBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/EmptyResilienceOptions.cs
Labels: v8

#1314 Enhance `OnHedgingArguments`
  src/Polly.Core/Hedging/Controller/HedgingHandler.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActionGeneratorArgumentsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActions.cs
  test/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
Labels: v8

#1316 The options that handle outcomes now have sensible defaults
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  test/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
Labels: v8

#1317 Update README.md with v8 alpha announcement
  README.md
Labels: v8

#1315 The deafult RateLimiterStrategyOptions instance is now valid
  src/Polly.RateLimiting/RateLimiterConstants.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterStrategyOptionsTests.cs
Labels: v8

#1320 Fix OnHedging not being called
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
Labels: v8

#1321 Reduce allocations in telemetry
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TelemetryBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/MultipleStrategiesBenchmark.cs
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  bench/Polly.Core.Benchmarks/Utils/MeteringUtil.cs
  src/Polly.Core/Telemetry/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.Pool.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.cs
  src/Polly.Core/Utils/ObjectPool.cs
  src/Polly.Extensions/Telemetry/EnrichmentContext.Pool.cs
  src/Polly.Extensions/Telemetry/EnrichmentContext.cs
  src/Polly.Extensions/Telemetry/EnrichmentUtil.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Utils/ObjectPoolTests.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1322 Add new issue test that demonstrates library scenario
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.cs
Labels: v8

#1325 Fix relative links
  samples/README.md
Labels: documentation, bug fix, v8

#1327 API feedback
  bench/Polly.Core.Benchmarks/ResilienceStrategyProviderBenchmark.cs
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  samples/GenericStrategies/Program.cs
  samples/Intro/Program.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Registry/ResilienceStrategyProvider.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyProviderTests.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs
  test/Polly.Extensions.Tests/ReloadableResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyBuilderExtensionsTests.cs
Labels: v8

#1326 Introduce ExecutionAttemptArguments
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  src/Polly.Core/Hedging/Controller/HedgingController.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Telemetry/ExecutionAttemptArguments.Pool.cs
  src/Polly.Core/Telemetry/ExecutionAttemptArguments.cs
  src/Polly.Core/Telemetry/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Core/Utils/TimeProvider.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions/Utils/TelemetryUtil.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingControllerTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingTimeProvider.cs
  test/Polly.Core.Tests/Helpers/FakeTimeProvider.cs
  test/Polly.Core.Tests/Issues/IssuesTests.cs
  test/Polly.Core.Tests/Retry/OnRetryArgumentsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Telemetry/ExecutionAttemptArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Utils/TelemetryUtilTests.cs
  test/Polly.TestUtils/MeteringEvent.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1330 Introduce OutcomeResilienceStrategy and drop some internals
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RetryBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/MultipleStrategiesBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/CircuitBreaker/Health/HealthMetrics.cs
  src/Polly.Core/Fallback/FallbackHandler.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Core/Hedging/Controller/HedgingHandler.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Outcome.cs
  src/Polly.Core/OutcomeArguments.cs
  src/Polly.Core/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Utils/EventInvoker.cs
  src/Polly.Core/Utils/GeneratorInvoker.cs
  src/Polly.Core/Utils/OutcomeResilienceStrategy.cs
  src/Polly.Core/Utils/PredicateInvoker.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackHandlerTests.cs
  test/Polly.Core.Tests/Fallback/FallbackHelper.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingHelper.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/EventInvokerTests.cs
  test/Polly.Core.Tests/Utils/GeneratorInvokerTests.cs
  test/Polly.Core.Tests/Utils/OutcomeResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/PredicateInvokerTests.cs
Labels: v8

#1332 Allow implicit conversion of `PredicateBuilder` to delegates
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PredicateBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/PredicateBenchmark.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/PredicateBuilder.Operators.cs
  src/Polly.Core/PredicateBuilder.TResult.cs
  src/Polly.Core/PredicateBuilder.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/PredicateBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
Labels: v8

#1336 Add net6.0 and net7.0 to Polly
  src/Polly/CompatibilitySuppressions.xml
  src/Polly/Polly.csproj
Labels: CI/build, v8

#1339 Sync TimeProvider and cleanup
  Polly.sln
  bench/Polly.Core.Benchmarks/GenericOverheadBenchmark.cs
  bench/Polly.Core.Benchmarks/HedgingBenchmark.cs
  bench/Polly.Core.Benchmarks/PredicateBenchmark.cs
  bench/Polly.Core.Benchmarks/Program.cs
  bench/Polly.Core.Benchmarks/Utils/MeteringUtil.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/CircuitBreaker/Health/RollingHealthMetrics.cs
  src/Polly.Core/CircuitBreaker/Health/SingleHealthMetrics.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Outcome.TResult.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/ToBeRemoved/TimeProvider.cs
  src/Polly.Core/Utils/DefaultPredicates.cs
  src/Polly.Core/Utils/OutcomeResilienceStrategy.cs
  src/Polly.Core/Utils/TimeProvider.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Telemetry/EnrichmentUtil.cs
  src/Polly.Extensions/Telemetry/TelemetryOptions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/BrokenCircuitExceptionTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/AdvancedCircuitBehaviorTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Health/HealthMetricsTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingControllerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActions.cs
  test/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingTimeProvider.cs
  test/Polly.Core.Tests/Hedging/PrimaryStringTasks.cs
  test/Polly.Core.Tests/Helpers/FakeTimeProvider.cs
  test/Polly.Core.Tests/Issues/IssuesTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Telemetry/ExecutionAttemptArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Utils/ExceptionUtilitiesTests.cs
  test/Polly.Core.Tests/Utils/OutcomeResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/ReloadableResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/SystemTimeProviderTests.cs
  test/Polly.Core.Tests/Utils/TypeNameFormatterTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs
  test/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Utils/TelemetryUtilTests.cs
Labels: v8

#1340 Fix hedging being cancelled too early
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
Labels: v8

#1341 Fix logging of execution attempt
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.TestUtils/FakeLogger.cs
Labels: v8

#1346 Expose Randomizer property and use it in retry strategy
  src/Polly.Core/ResilienceStrategyBuilderBase.cs
  src/Polly.Core/ResilienceStrategyBuilderContext.cs
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategyBuilderExtensions.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderContextTests.cs
  test/Polly.Core.Tests/ResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
Labels: v8

#1347 Update changelog
  CHANGELOG.md
  README.md
Labels: v8

#1351 Drop custom validation attributes
  src/Polly.Core/CircuitBreaker/AdvancedCircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Timeout/TimeoutAttribute.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategyBuilderExtensions.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.Core/Timeout/TimeoutUtil.cs
  src/Polly.Core/Utils/TimeSpanAttribute.cs
  test/Polly.Core.Tests/CircuitBreaker/AdvancedCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/CircuitBreaker/SimpleCircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutAttributeTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutTestUtils.cs
  test/Polly.Core.Tests/Utils/TimeSpanAttributeTests.cs
Labels: v8

#1354 Skip mutation tests for tagged builds
  .github/workflows/build.yml
Labels: CI/build, v8

#1353 Update CHANGELOG
  CHANGELOG.md
  Directory.Packages.props
  README.md
Labels: documentation, v8

#1355 Drop TimeProvider.Delay
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/ToBeRemoved/TimeProvider.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingTimeProvider.cs
  test/Polly.Core.Tests/Helpers/MockTimeProvider.cs
  test/Polly.Core.Tests/Issues/IssuesTests.HandleMultipleResults_898.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/TimeProviderExtensionsTests.cs
Labels: v8

#1358 Fix race conditions in tests
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingTimeProvider.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1359 Simplify the logging
  Directory.Packages.props
  src/Polly.Extensions/Telemetry/Log.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
Labels: v8

#1361 Introduce ResilienceEventSeverity
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Telemetry/ResilienceEvent.cs
  src/Polly.Core/Telemetry/ResilienceEventSeverity.cs
  src/Polly.Core/Telemetry/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.Pool.cs
  src/Polly.Core/Telemetry/TelemetryEventArguments.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.Core/Utils/ReloadableResilienceStrategy.cs
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceContextExtensions.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryUtil.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/ResilienceContextTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceEventTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Utils/ReloadableResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1363 Upload coverage reports
  .github/workflows/build.yml
Labels: CI/build

#1368 Kill mutant
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
Labels: v8

#1374 Simplify handling of reloads
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/Registry/ResilienceStrategyRegistry.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Utils/OptionsReloadHelper.cs
  src/Polly.Extensions/Utils/OptionsReloadHelperRegistry.cs
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/ReloadableResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Utils/OptionsReloadHelperTests.cs
Labels: v8

#1375 Allow reusing CircuitBreakerManualControl across multiple CBs
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerManualControlTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyBuilderTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerStateProviderTests.cs
Labels: v8
