Repository App-vNext/Polly, pull requests merged in 2023-08, with the labels that each got.

#1455 Simplify file names
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/ReactiveResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategy.Async.cs
  src/Polly.Core/ResilienceStrategy.AsyncT.cs
  src/Polly.Core/ResilienceStrategyT.Async.cs
  src/Polly.Core/ResilienceStrategyT.Sync.cs
  src/Polly.Core/ResilienceStrategyT.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  test/Polly.Core.Tests/ResilienceStrategyTTests.Async.cs
  test/Polly.Core.Tests/ResilienceStrategyTTests.Sync.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.Async.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.AsyncT.cs
  test/Polly.Core.Tests/Utils/ReactiveResilienceStrategyTests.cs
Labels: v8

#1457 Improve `MultipleStrategiesBenchmark`
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  bench/Polly.Core.Benchmarks/MultipleStrategiesBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
Labels: v8

#1456 Elaborate about synchronous vs asynchronous executions
  src/Polly.Core/README.md
Labels: documentation, v8

#1458 Fix some typos in XML docs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategyT.Async.cs
Labels: v8

#1460 Make `ReactiveResilienceStrategy` public
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ReactiveResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Utils/CompositeResilienceStrategy.DebuggerProxy.cs
Labels: v8

#1462 Make the `ReactiveResilienceStrategy` type-safe
  src/Polly.Core/CircuitBreaker/CircuitBreakerCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ReactiveResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Retry/RetryCompositeStrategyBuilderExtensions.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Utils/ReactiveResilienceStrategyBridge.cs
  src/Polly.Core/Utils/StrategyHelper.cs
  src/Polly.Testing/ResilienceStrategyExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerCompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/Fallback/FallbackCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/ReactiveResilienceStrategyBridgeTests.cs
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8

#1463 Use `StrategyHelper` for safe executions and drop redundant methods
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/ReactiveResilienceStrategy.cs
  src/Polly.Core/ResilienceStrategy.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/StrategyHelperTests.cs
Labels: v8

#1464 Drop unnecessary allocation in circuit breaker
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
Labels: v8

#1466 Fix unstable build
  test/Polly.Extensions.Tests/Issues/IssuesTests.cs
  test/Polly.Extensions.Tests/NonParallelizableCollection.cs
  test/Polly.Extensions.Tests/NonParallelizableCollectionFixture.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
Labels: v8

#1467 Improve samples
  samples/Extensibility/Program.cs
  samples/GenericStrategies/Program.cs
  samples/Intro/Program.cs
  samples/README.md
Labels: v8

#1468 Specify DebuggerDisplay for ReactiveResilienceStrategyBridge
  src/Polly.Core/Utils/ReactiveResilienceStrategyBridge.cs
Labels: v8

#1469 Drop the `Extensions` from `Polly.Extensions` namespace
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerManualControl.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/LegacySupport.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceStrategyT.Async.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Utils/CompositeResilienceStrategy.cs
  src/Polly.Core/Utils/TaskHelper.cs
  src/Polly.Extensions/DependencyInjection/AddResilienceStrategyContext.cs
  src/Polly.Extensions/DependencyInjection/ConfigureResilienceStrategyRegistryOptions.cs
  src/Polly.Extensions/DependencyInjection/PollyDependencyInjectionKeys.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.Extensions/Registry/ConfigureBuilderContextExtensions.cs
  src/Polly.Extensions/Telemetry/EnrichmentContext.Pool.cs
  src/Polly.Extensions/Telemetry/EnrichmentContext.cs
  src/Polly.Extensions/Telemetry/EnrichmentUtil.cs
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceContextExtensions.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryCompositeStrategyBuilderExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryOptions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Extensions/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions/Utils/OptionsReloadHelper.cs
  src/Polly.Testing/ResilienceStrategyExtensions.cs
  src/Polly/Utilities/Wrappers/ResilienceContextFactory.cs
  test/Polly.Core.Tests/CircuitBreaker/OnCircuitHalfOpenedArgumentsTests.cs
  test/Polly.Core.Tests/Utils/LegacySupportTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyDependencyInjectionKeysTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Extensions.Tests/ReloadableResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Telemetry/EnrichmentContextTests.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryOptionsTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Utils/OptionsReloadHelperTests.cs
  test/Polly.Extensions.Tests/Utils/TelemetryUtilTests.cs
  test/Polly.RateLimiting.Tests/ResilienceRateLimiterTests.cs
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8

#1472 Remove Moq
  Directory.Packages.props
  eng/Test.targets
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/AdvancedCircuitBehaviorTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/CompositeStrategyBuilderContextTests.cs
  test/Polly.Core.Tests/CompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/CancellationTokenSourcePoolTests.cs
  test/Polly.Core.Tests/Utils/DisposeHelperTests.cs
  test/Polly.Extensions.Tests/Utils/OptionsReloadHelperTests.cs
  test/Polly.RateLimiting.Tests/OnRateLimiterRejectedArgumentsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  test/Polly.RateLimiting.Tests/ResilienceRateLimiterTests.cs
  test/Polly.Specs/Polly.Specs.csproj
  test/Polly.Specs/Registry/PolicyRegistrySpecs.cs
  test/Polly.Specs/Registry/ReadOnlyPolicyRegistrySpecs.cs
  test/Polly.TestUtils/Polly.TestUtils.csproj
  test/Polly.TestUtils/TestUtilities.cs
Labels: CI/build, dependencies, .NET

#1474 Add new metering tests to cover uncovered lines
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1475 Default names for individual resilience strategies
  src/Polly.Core/CircuitBreaker/CircuitBreakerConstants.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/Fallback/FallbackConstants.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Polly.Core/Hedging/HedgingConstants.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/Retry/RetryConstants.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Timeout/TimeoutConstants.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.RateLimiting/RateLimiterConstants.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerOptionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackStrategyOptionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutStrategyOptionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterStrategyOptionsTests.cs
Labels: v8

#1482 Drop `TelemetryResilienceStrategy`
  src/Polly.Core/CompositeStrategyBuilderBase.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/OnHedgingArguments.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Telemetry/ExecutionAttemptArguments.Pool.cs
  src/Polly.Core/Telemetry/ExecutionAttemptArguments.cs
  src/Polly.Core/Telemetry/PipelineExecutedArguments.Pool.cs
  src/Polly.Core/Telemetry/PipelineExecutedArguments.cs
  src/Polly.Core/Telemetry/PipelineExecutingArguments.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Core/Utils/CompositeResilienceStrategy.cs
  src/Polly.Extensions/README.md
  src/Polly.Extensions/Telemetry/ResilienceTelemetryDiagnosticSource.cs
  src/Polly.Extensions/Telemetry/TelemetryCompositeStrategyBuilderExtensions.cs
  src/Polly.Extensions/Telemetry/TelemetryResilienceStrategy.cs
  src/Polly.Testing/InnerStrategiesDescriptor.cs
  src/Polly.Testing/PublicAPI.Unshipped.txt
  src/Polly.Testing/ResilienceStrategyDescriptor.cs
  src/Polly.Testing/ResilienceStrategyExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerCompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/CompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/Fallback/FallbackCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/GenericCompositeStrategyBuilderTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/OnHedgingArgumentsTests.cs
  test/Polly.Core.Tests/Polly.Core.Tests.csproj
  test/Polly.Core.Tests/Registry/ResilienceStrategyRegistryTests.cs
  test/Polly.Core.Tests/ResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Telemetry/ExecutionAttemptArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/PipelineExecutedArgumentsTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Utils/CompositeResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryResilienceStrategyTests.cs
  test/Polly.Extensions.Tests/Utils/ResilienceContextExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterCompositeStrategyBuilderExtensionsTests.cs
  test/Polly.TestUtils/TestUtilities.cs
  test/Polly.Testing.Tests/ResilienceStrategyExtensionsTests.cs
Labels: v8

#1484 API Review feedback (1)
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Timeout/OnTimeoutArguments.cs
  src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/ResilienceRateLimiter.cs
  test/Polly.Core.Tests/Timeout/TimeoutResilienceStrategyTests.cs
  test/Polly.Core.Tests/Timeout/TimeoutTestUtils.cs
  test/Polly.RateLimiting.Tests/ResilienceRateLimiterTests.cs
Labels: v8

#1485 API Review Feedback (2)
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/Retry/RetryResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/StrategyBuilderContext.cs
  src/Polly.Core/Telemetry/ResilienceTelemetrySource.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions/DependencyInjection/PollyDependencyInjectionKeys.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  test/Polly.Core.Tests/GenericResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  test/Polly.Core.Tests/StrategyBuilderContextTests.cs
  test/Polly.Core.Tests/Telemetry/ResilienceStrategyTelemetryTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyDependencyInjectionKeysTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/Telemetry/ResilienceTelemetryDiagnosticSourceTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1487 Improve documentation
  src/Polly.Core/CircuitBreaker/CircuitBreakerStrategyOptions.TResult.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.TResult.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
Labels: v8

#1488 Fix metering tests
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
Labels: v8

#1490 Hide validation APIs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/ResilienceValidationContext.cs
  src/Polly.Extensions/Polly.Extensions.csproj
  src/Polly.Extensions/Telemetry/TelemetryResiliencePipelineBuilderExtensions.cs
Labels: v8

#1489 Logging improvements
  src/Polly.Extensions/Telemetry/Log.cs
Labels: v8

#1491 Hide/drop some unused APIs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/README.md
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistryOptions.cs
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/ResiliencePropertyKey.cs
  src/Polly.Core/StrategyBuilderContext.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Polly.Extensions/DependencyInjection/AddResiliencePipelineContext.cs
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.Extensions/README.md
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceContextExtensions.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryListenerImpl.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePropertyKeyTests.cs
  test/Polly.Core.Tests/StrategyBuilderContextTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
  test/Polly.Specs/ResiliencePipelineConversionExtensionsTests.cs
Labels: v8

#1492 Cleanup internals
  bench/Polly.Core.Benchmarks/BridgeBenchmark.cs
  bench/Polly.Core.Benchmarks/ResiliencePipelineBenchmark.cs
  src/Polly.Core/NullResiliencePipeline.TResult.cs
  src/Polly.Core/NullResiliencePipeline.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ResiliencePipelineRegistry.TResult.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
  src/Polly.Core/ResiliencePipeline.Async.cs
  src/Polly.Core/ResiliencePipeline.AsyncT.cs
  src/Polly.Core/ResiliencePipeline.Sync.cs
  src/Polly.Core/ResiliencePipeline.SyncT.cs
  src/Polly.Core/ResiliencePipeline.cs
  src/Polly.Core/ResiliencePipelineBuilder.TResult.cs
  src/Polly.Core/ResiliencePipelineBuilder.cs
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/ResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/ResiliencePipelineT.Async.cs
  src/Polly.Core/ResiliencePipelineT.Sync.cs
  src/Polly.Core/ResiliencePipelineT.cs
  src/Polly.Core/Utils/CompositeResiliencePipeline.DebuggerProxy.cs
  src/Polly.Core/Utils/CompositeResiliencePipeline.cs
  src/Polly.Core/Utils/PipelineComponent.Bridge.cs
  src/Polly.Core/Utils/PipelineComponent.Composite.cs
  src/Polly.Core/Utils/PipelineComponent.Reloadale.cs
  src/Polly.Core/Utils/PipelineComponent.cs
  src/Polly.Core/Utils/ReloadableResiliencePipeline.cs
  src/Polly.Core/Utils/ResiliencePipelineBridge.TResult.cs
  src/Polly.Core/Utils/ResiliencePipelineBridge.cs
  src/Polly.Core/Utils/SynchronousExecutionHelper.cs
  src/Polly.Core/Utils/TaskHelper.cs
  src/Polly.Core/Utils/ValidationContextExtensions.cs
  src/Polly.Core/Utils/ValidationHelper.cs
  src/Polly.Testing/ResiliencePipelineExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/GenericResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/NullResiliencePipelineTests.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineProviderTests.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Async.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Sync.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.AsyncT.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/CompositeResiliencePipelineTests.cs
  test/Polly.Core.Tests/Utils/PipelineComponents/BridgePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/PipelineComponents/CompositePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/PipelineComponents/PipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/StrategyHelperTests.cs
  test/Polly.Core.Tests/Utils/TaskHelperTests.cs
  test/Polly.Core.Tests/Utils/ValidationHelperTests.cs
  test/Polly.TestUtils/ResilienceStrategyExtensions.cs
  test/Polly.TestUtils/TestResiliencePipeline.TResult.cs
Labels: v8

#1493 ResilienceContextPool improvements
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResilienceContextCreationArguments.cs
  src/Polly.Core/ResilienceContextPool.Shared.cs
  src/Polly.Core/ResilienceContextPool.cs
  src/Polly/Utilities/Wrappers/ResilienceContextFactory.cs
  test/Polly.Core.Tests/ResilienceContextPoolTests.cs
Labels: v8

#1494 Hide IsSynchronous property
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceContext.cs
  test/Polly.Specs/ResiliencePipelineConversionExtensionsTests.cs
Labels: v8

#1495 Drop unused ResiliencePipelineRegistry APIs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ResiliencePipelineRegistry.TResult.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs
Labels: v8

#1497 Move pipeline-related internals into `Pipeline` folder
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
  src/Polly.Core/ResiliencePipeline.Async.cs
  src/Polly.Core/ResiliencePipeline.AsyncT.cs
  src/Polly.Core/ResiliencePipeline.Sync.cs
  src/Polly.Core/ResiliencePipeline.SyncT.cs
  src/Polly.Core/ResiliencePipeline.cs
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/ResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/ResiliencePipelineT.cs
  src/Polly.Core/Utils/Pipeline/BridgeComponent.TResult.cs
  src/Polly.Core/Utils/Pipeline/BridgeComponent.cs
  src/Polly.Core/Utils/Pipeline/BridgeComponentBase.cs
  src/Polly.Core/Utils/Pipeline/ComponentDisposeHelper.cs
  src/Polly.Core/Utils/Pipeline/CompositeComponent.cs
  src/Polly.Core/Utils/Pipeline/CompositeComponentDebuggerProxy.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponent.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponentFactory.cs
  src/Polly.Core/Utils/Pipeline/ReloadableComponent.cs
  src/Polly.Core/Utils/PipelineComponent.Bridge.cs
  src/Polly.Core/Utils/PipelineComponent.Composite.cs
  src/Polly.Core/Utils/PipelineComponent.Reloadale.cs
  src/Polly.Core/Utils/PipelineComponent.cs
  src/Polly.Testing/ResiliencePipelineExtensions.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/GenericResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Async.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Sync.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.cs
  test/Polly.Core.Tests/Telemetry/ExecutionAttemptArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/PipelineExecutedArgumentsTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryEventArgumentsTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/BridgePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/CompositePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/PipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/ReloadablePipelineComponentTests.cs
Labels: v8

#1505 Minor ResiliencePipelineRegistry cleanup of internals
  src/LegacySupport/ConcurrentDictionaryExtensions.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.TResult.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
Labels: v8

#1506 API Review Feedback
  bench/Polly.Core.Benchmarks/BridgeBenchmark.cs
  bench/Polly.Core.Benchmarks/ResiliencePipelineBenchmark.cs
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Core/Outcome.TResult.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResiliencePipeline.cs
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/ResiliencePipelineT.cs
  src/Polly.Core/Telemetry/ResilienceStrategyTelemetry.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponent.cs
  src/Polly.Extensions/README.md
  src/Polly.Extensions/Telemetry/Log.cs
  src/Polly.Extensions/Telemetry/ResilienceContextExtensions.cs
  src/Polly.Extensions/Telemetry/ResilienceTelemetryTags.cs
  src/Polly.Extensions/Telemetry/TelemetryListenerImpl.cs
  src/Polly.RateLimiting/OnRateLimiterRejectedArguments.cs
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineProviderTests.cs
  test/Polly.Core.Tests/ResilienceContextPoolTests.cs
  test/Polly.Core.Tests/ResilienceContextTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Async.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.AsyncT.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/CompositePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/PipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/ReloadablePipelineComponentTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
  test/Polly.Extensions.Tests/Utils/ResilienceContextExtensionsTests.cs
  test/Polly.RateLimiting.Tests/OnRateLimiterRejectedArgumentsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
Labels: v8

#1508 Minor API cleanup
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/OnRetryArguments.cs
  src/Polly.Testing/PublicAPI.Unshipped.txt
  src/Polly.Testing/ResiliencePipelineDescriptor.cs
  src/Polly.Testing/ResilienceStrategyDescriptor.cs
  test/Polly.Core.Tests/Retry/OnRetryArgumentsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
Labels: v8

#1509 Clenaup rate limiter API
  src/Polly.RateLimiting/DisposeWrapper.cs
  src/Polly.RateLimiting/PublicAPI.Unshipped.txt
  src/Polly.RateLimiting/RateLimiterArguments.cs
  src/Polly.RateLimiting/RateLimiterResiliencePipelineBuilderExtensions.cs
  src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs
  src/Polly.RateLimiting/RateLimiterStrategyOptions.cs
  src/Polly.RateLimiting/ResilienceRateLimiter.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.PartitionedRateLimiter_1365.cs
  test/Polly.RateLimiting.Tests/RateLimiterResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  test/Polly.RateLimiting.Tests/ResilienceRateLimiterTests.cs
Labels: v8

#1510 Cleanup ResiliencePipelineRegistry internals
  src/Polly.Core/Registry/RegistryPipelineComponentBuilder.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.TResult.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
Labels: v8

#1511 Allow to dispose linked resources on pipeline disposal
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Registry/ConfigureBuilderContext.cs
  src/Polly.Core/Registry/RegistryPipelineComponentBuilder.cs
  src/Polly.Core/Utils/Pipeline/ComponentWithDisposeCallbacks.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponentFactory.cs
  src/Polly.Extensions/DependencyInjection/AddResiliencePipelineContext.cs
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.Testing/ResiliencePipelineExtensions.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/ComponentWithDisposeCallbacksTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/PipelineComponentFactoryTests.cs
  test/Polly.Extensions.Tests/DisposablePipelineTests.cs
  test/Polly.Testing.Tests/ResiliencePipelineExtensionsTests.cs
Labels: v8

#1521 API Review Feedback
  bench/Polly.Core.Benchmarks/Utils/Helper.Hedging.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.Retry.cs
  src/Polly.Core/DelayBackoffType.cs
  src/Polly.Core/Hedging/HedgingActionGeneratorArguments.cs
  src/Polly.Core/Hedging/HedgingConstants.cs
  src/Polly.Core/Hedging/HedgingResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.TResult.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/RetryConstants.cs
  src/Polly.Core/Retry/RetryDelayGeneratorArguments.cs
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  test/Polly.Core.Tests/Hedging/HedgingResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Issues/IssuesTests.HandleMultipleResults_898.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/Retry/RetryConstantsTests.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
  test/Polly.Core.Tests/Retry/RetryResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Retry/RetryStrategyOptionsTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Specs/ResiliencePipelineConversionExtensionsTests.cs
Labels: v8

#1523 Cleanup Outcome internals and drop unused hedging and fallbacks APIs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerStateProvider.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/Fallback/FallbackHandler.cs
  src/Polly.Core/Fallback/FallbackResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/Fallback/FallbackResilienceStrategy.cs
  src/Polly.Core/Fallback/FallbackStrategyOptions.cs
  src/Polly.Core/Hedging/Controller/HedgingExecutionContext.cs
  src/Polly.Core/Hedging/Controller/HedgingHandler.cs
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Hedging/HedgingResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/Hedging/HedgingResilienceStrategy.cs
  src/Polly.Core/Hedging/HedgingStrategyOptions.cs
  src/Polly.Core/Outcome.TResult.cs
  src/Polly.Core/Outcome.cs
  src/Polly.Core/Utils/Pipeline/BridgeComponent.TResult.cs
  src/Polly.Core/Utils/TaskHelper.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerStateProviderTests.cs
  test/Polly.Core.Tests/Fallback/FallbackHandlerTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingHelper.cs
  test/Polly.Core.Tests/Hedging/HedgingResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/OutcomeTests.cs
  test/Polly.TestUtils/TestUtilities.cs
Labels: v8

#1524 Improve debugging experience for `ResilienceProperties`
  src/Polly.Core/ResilienceProperties.cs
Labels: v8

#1522 Protect against retry delay overflows
  src/Polly.Core/Retry/RetryHelper.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
Labels: v8

#1525 Fix DelayAsync extension
  src/Polly.Core/DelayBackoffType.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Utils/TimeProviderExtensions.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
  test/Polly.Core.Tests/Utils/TimeProviderExtensionsTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.StrategiesPerEndpoint_1365.cs
  test/Polly.Specs/ResiliencePipelineConversionExtensionsTests.cs
Labels: v8

#1526 Updates for alpha.9
  CHANGELOG.md
  Directory.Packages.props
  README.md
  samples/DependencyInjection/Program.cs
  samples/Extensibility/Program.cs
  samples/GenericStrategies/Program.cs
  samples/Intro/Program.cs
  samples/Retries/Program.cs
Labels: v8

#1528 Finalize the API review
  bench/Polly.Core.Benchmarks/CreationBenchmark.cs
  bench/Polly.Core.Benchmarks/PredicateBenchmark.cs
  bench/Polly.Core.Benchmarks/ResiliencePipelineBenchmark.cs
  bench/Polly.Core.Benchmarks/TelemetryBenchmark.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.CircuitBreaker.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.Hedging.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.MultipleStrategies.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.Retry.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  src/Polly.Core/Outcome.TResult.cs
  src/Polly.Core/Outcome.cs
  src/Polly.Core/PredicateResult.cs
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/README.md
  src/Polly.Core/Retry/RetryDelayGeneratorArguments.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Retry/RetryStrategyOptions.TResult.cs
  src/Polly.Core/Utils/DefaultPredicates.cs
  src/Polly.Core/Utils/Pipeline/CompositeComponent.cs
  src/Polly/CircuitBreaker/BrokenCircuitException.TResult.cs
  src/Polly/Properties/AssemblyInfo.cs
  src/Polly/PublicAPI.Shipped.txt
  test/Polly.Core.Tests/CircuitBreaker/BrokenCircuitExceptionTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Fallback/FallbackResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingControllerTests.cs
  test/Polly.Core.Tests/Hedging/Controller/HedgingExecutionContextTests.cs
  test/Polly.Core.Tests/Hedging/Controller/TaskExecutionTests.cs
  test/Polly.Core.Tests/Hedging/HedgingActionGeneratorArgumentsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingHandlerTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Hedging/HedgingResilienceStrategyTests.cs
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Issues/IssuesTests.FlowingContext_849.cs
  test/Polly.Core.Tests/Issues/IssuesTests.HandleMultipleResults_898.cs
  test/Polly.Core.Tests/OutcomeTests.cs
  test/Polly.Core.Tests/PredicateResultTests.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Core.Tests/ResiliencePipelineTTests.Async.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.AsyncT.cs
  test/Polly.Core.Tests/Retry/RetryDelayGeneratorArgumentsTests.cs
  test/Polly.Core.Tests/Retry/RetryResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/CompositePipelineComponentTests.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs
  test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs
  test/Polly.RateLimiting.Tests/RateLimiterResilienceStrategyTests.cs
  test/Polly.Specs/ResiliencePipelineConversionExtensionsTests.cs
  test/Polly.Testing.Tests/ResiliencePipelineExtensionsTests.cs
Labels: v8

#1529 Disposing pipeline should not dispose external inner pipeline
  src/Polly.Core/ResiliencePipelineBuilderBase.cs
  src/Polly.Core/Utils/Pipeline/ExternalComponent.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponentFactory.cs
  src/Polly.Testing/ResiliencePipelineExtensions.cs
  test/Polly.Core.Tests/GenericResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Extensions.Tests/DisposablePipelineTests.cs
  test/Polly.Testing.Tests/ResiliencePipelineExtensionsTests.cs
Labels: v8

#1530 Clean duplications around disposing the pipelines
  src/Polly.Core/Registry/ResiliencePipelineRegistry.TResult.cs
  src/Polly.Core/Registry/ResiliencePipelineRegistry.cs
  src/Polly.Core/Utils/Pipeline/BridgeComponentBase.cs
  src/Polly.Core/Utils/Pipeline/ComponentDisposeHelper.cs
  src/Polly.Core/Utils/Pipeline/ComponentWithDisposeCallbacks.cs
  src/Polly.Core/Utils/Pipeline/CompositeComponent.cs
  src/Polly.Core/Utils/Pipeline/ExternalComponent.cs
  src/Polly.Core/Utils/Pipeline/PipelineComponent.cs
  src/Polly.Core/Utils/Pipeline/ReloadableComponent.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/Registry/ResiliencePipelineRegistryTests.cs
  test/Polly.Core.Tests/ResiliencePipelineBuilderTests.cs
  test/Polly.Core.Tests/ResiliencePipelineTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/BridgePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/ComponentWithDisposeCallbacksTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/CompositePipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/PipelineComponentTests.cs
  test/Polly.Core.Tests/Utils/Pipeline/ReloadablePipelineComponentTests.cs
  test/Polly.Extensions.Tests/DisposablePipelineTests.cs
  test/Polly.Extensions.Tests/Registry/ConfigureBuilderContextExtensionsTEsts.cs
  test/Polly.RateLimiting.Tests/RateLimiterResiliencePipelineBuilderExtensionsTests.cs
  test/Polly.Testing.Tests/ResiliencePipelineExtensionsTests.cs
Labels: v8

#1531 Updates for beta.1
  CHANGELOG.md
  Directory.Packages.props
  README.md
  samples/GenericStrategies/Program.cs
  samples/Intro/Program.cs
  samples/Retries/Program.cs
Labels: documentation, v8

#1532 Drop unused internal property
  src/Polly.Core/Registry/RegistryPipelineComponentBuilder.cs
Labels: v8
