Repository App-vNext/Polly, pull requests merged in 2024-09, with the labels that each got.

#2279 Fix NuGet badges
  README.md
  package-readme.md
Labels: documentation, bug fix

#2292 Suppress S3234 warnings
  src/Polly/Utilities/TimedLock.cs
Labels: CI/build

#2291 Report last attempt as error if it would be handled
  docs/advanced/telemetry.md
  docs/strategies/retry.md
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Telemetry/TelemetryUtil.cs
  src/Snippets/Docs/Telemetry.cs
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Telemetry/TelemetryUtilTests.cs
Labels: enhancement

#2302 Fix ide0002 style rule
  src/Polly.Core/ResilienceValidationContext.cs
  src/Polly/AsyncPolicy.ExecuteOverloads.cs
  src/Polly/AsyncPolicy.TResult.ExecuteOverloads.cs
  src/Polly/Policy.ExecuteOverloads.cs
  src/Polly/Policy.TResult.ExecuteOverloads.cs
  src/Polly/Utilities/TimedLock.cs
  src/Snippets/Docs/ResiliencePipelines.cs
Labels: CI/build

#2300 Update ResilienceProperties to correctly handle null values
  src/Polly.Core/ResilienceProperties.cs
  test/Polly.Core.Tests/ResiliencePropertiesTests.cs
Labels: bug fix

#2305 Downgrade sign tool
  .config/dotnet-tools.json
Labels: dependencies, .NET

#2313 Fix issue 2288
  test/Polly.Core.Tests/Hedging/HedgingStrategyOptionsTests.cs
  test/Polly.Core.Tests/Polly.Core.Tests.csproj
  test/Polly.Core.Tests/xunit.runner.json
Labels: CI/build

#2316 Remove CA2211 NoWarn
  src/Polly/Polly.csproj
  src/Polly/Utilities/SystemClock.cs
  src/Polly/Utilities/TaskHelper.cs
Labels: CI/build
