Repository App-vNext/Polly, pull requests merged in 2024-06, with the labels that each got.

#2148 Removing Warnings SA1108 and SA1118 from NoWarn list
  src/Polly/Polly.csproj
  src/Polly/Timeout/TimeoutEngine.cs
Labels: CI/build

#2164 Fix retry delay going negative for large retries with exponential delays
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  test/Polly.Core.Tests/Issues/IssuesTests.InfiniteRetry_2163.cs
  test/Polly.Core.Tests/Retry/RetryHelperTests.cs
  test/Polly.Core.Tests/Utils/CancellationTokenSourcePoolTests.cs
Labels: bug fix

#2166 Handle nested inner exceptions
  src/Polly.Core/PredicateBuilder.TResult.cs
  test/Polly.Core.Tests/PredicateBuilderTests.cs
Labels: bug fix

#2169 Update sponsors
  README.md
  logos/microsoft.png
Labels: documentation
