Repository App-vNext/Polly, pull requests merged in 2024-01, with the labels that each got.

#1860 Added ConfigureResiliencePipelineRegistry<TKey> method to IServiceCollection to allow deferred configuration of ResiliencePipelineRegistry<TKey>
  docs/advanced/dependency-injection.md
  src/Polly.Extensions/DependencyInjection/AddResiliencePipelinesContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Snippets/Docs/DependencyInjection.cs
  test/Polly.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs
Labels: enhancement

#1876 Fix grammar
  src/Polly.Extensions/DependencyInjection/AddResiliencePipelinesContext.cs
  src/Polly.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs
Labels: documentation

#1879 Run workflows on release branches
  .github/workflows/actions-lint.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependabot-approve.yml
  .github/workflows/dependency-review.yml
  .github/workflows/gh-pages.yml
  .github/workflows/updater-approve.yml
Labels: enhancement, CI/build

#1882 Update CHANGELOG for 8.2.1
  CHANGELOG.md
Labels: documentation

#1888 Decrease the minimum allowed timeout
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
  test/Polly.Core.Tests/Timeout/TimeoutTestUtils.cs
Labels: enhancement

#1897 Fix typo
  docs/migration-v8.md
  src/Snippets/Docs/Migration.Wrap.cs
Labels: bug, documentation

#1883 Simmy docs
  .github/wordlist.txt
  docs/advanced/simmy.md
  docs/chaos/behavior.md
  docs/chaos/fault.md
  docs/chaos/index.md
  docs/chaos/latency.md
  docs/chaos/result.md
  docs/docfx.json
  docs/index.md
  docs/media/simmy-logo.png
  docs/strategies/circuit-breaker.md
  docs/toc.yml
  src/Polly.Core/Simmy/Fault/FaultStrategyOptions.cs
  src/Snippets/Docs/Chaos.Behavior.cs
  src/Snippets/Docs/Chaos.Fault.cs
  src/Snippets/Docs/Chaos.Latency.cs
  src/Snippets/Docs/Chaos.Result.cs
Labels: documentation

#1918 [Docs] Add clarification about property precedence
  docs/chaos/index.md
  docs/strategies/circuit-breaker.md
  docs/strategies/hedging.md
  docs/strategies/retry.md
  docs/strategies/timeout.md
Labels: documentation

#1922 [Docs] Replace textual descriptions of next delay calculation with diagrams
  docs/strategies/retry.md
Labels: enhancement, documentation

#1923 [Docs] Apply chaos selectively
  .github/wordlist.txt
  docs/chaos/index.md
  src/Snippets/Docs/Chaos.Index.cs
Labels: documentation

#1928 Got rid of IDE0044 warnings
  src/Polly/Bulkhead/AsyncBulkheadPolicy.cs
  src/Polly/Caching/CachePolicy.cs
  src/Polly/Fallback/AsyncFallbackPolicy.cs
  src/Polly/Fallback/FallbackPolicy.cs
  src/Polly/Polly.csproj
  src/Polly/Timeout/AsyncTimeoutPolicy.cs
  src/Polly/Timeout/TimeoutPolicy.cs
  src/Polly/Utilities/TimedLock.cs
Labels: enhancement, CI/build

#1927 [Doc] Integrating chaos pipeline
  docs/chaos/index.md
  src/Snippets/Docs/Chaos.Index.cs
Labels: documentation

#1930 Got rid of IDE0066, IDE0250, IDE0063 warnings
  src/Polly/Polly.csproj
  src/Polly/Utilities/EmptyStruct.cs
  src/Polly/Utilities/TimedLock.cs
  src/Polly/Wrap/AsyncPolicyWrapSyntax.cs
  src/Polly/Wrap/PolicyWrapSyntax.cs
Labels: enhancement, CI/build

#1931 Fix PipelineNameComparer example in documentation
  docs/advanced/dependency-injection.md
  src/Snippets/Docs/DependencyInjection.cs
Labels: bug, bug fix

#1935 Fix S6608/IDE1006/SA1414/CA1508 warnings in Polly.Specs project
  eng/analyzers/Stylecop.json
  src/Polly.Core/Registry/RegistryPipelineComponentBuilder.cs
  src/Polly/RateLimit/IRateLimiter.cs
  src/Polly/RateLimit/LockFreeTokenBucketRateLimiter.cs
  test/Polly.Specs/Caching/CacheAsyncSpecs.cs
  test/Polly.Specs/Caching/CacheSpecs.cs
  test/Polly.Specs/Caching/CacheTResultAsyncSpecs.cs
  test/Polly.Specs/Caching/CacheTResultSpecs.cs
  test/Polly.Specs/Caching/GenericCacheProviderAsyncSpecs.cs
  test/Polly.Specs/Caching/GenericCacheProviderSpecs.cs
  test/Polly.Specs/Caching/ResultTtlSpecs.cs
  test/Polly.Specs/Helpers/Bulkhead/AnnotatedOutputHelper.cs
  test/Polly.Specs/Helpers/Bulkhead/TraceableAction.cs
  test/Polly.Specs/Helpers/Caching/StubCacheKeyStrategy.cs
  test/Polly.Specs/Helpers/Caching/StubCacheProvider.cs
  test/Polly.Specs/Helpers/Caching/StubErroringCacheProvider.cs
  test/Polly.Specs/Helpers/RateLimit/IRateLimiterExtensions.cs
  test/Polly.Specs/PolicyContextAndKeyAsyncSpecs.cs
  test/Polly.Specs/PolicyContextAndKeySpecs.cs
  test/Polly.Specs/Polly.Specs.csproj
  test/Polly.Specs/RateLimit/RateLimitPolicySpecsBase.cs
  test/Polly.Specs/RateLimit/TokenBucketRateLimiterTestsBase.cs
  test/Polly.Specs/Registry/ConcurrentPolicyRegistrySpecs.cs
Labels: enhancement, CI/build

#1936 Fix SA1602/S6608/S4144 warnings
  test/Polly.Core.Tests/Polly.Core.Tests.csproj
  test/Polly.Core.Tests/Retry/RetryResilienceStrategyTests.cs
  test/Polly.Core.Tests/Utils/ObjectPoolTests.cs
  test/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj
  test/Polly.Extensions.Tests/ReloadableResiliencePipelineTests.cs
  test/Polly.Specs/Fallback/FallbackTResultAsyncSpecs.cs
  test/Polly.Specs/PolicyTResultAsyncSpecs.cs
  test/Polly.Specs/Polly.Specs.csproj
  test/Polly.TestUtils/Polly.TestUtils.csproj
Labels: enhancement, CI/build

#1938 Fix SA1113/CA1200/SA1805/SA1629/SA1407/SA1127 warnings
  src/Polly/Bulkhead/BulkheadRejectedException.cs
  src/Polly/Caching/AbsoluteTtl.cs
  src/Polly/Caching/Ttl.cs
  src/Polly/CircuitBreaker/AdvancedCircuitController.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/CircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/ConsecutiveCountCircuitController.cs
  src/Polly/Context.Dictionary.cs
  src/Polly/Fallback/AsyncFallbackPolicy.cs
  src/Polly/Fallback/FallbackPolicy.cs
  src/Polly/Policy.HandleSyntax.cs
  src/Polly/PolicyBuilder.OrSyntax.cs
  src/Polly/PolicyBuilder.cs
  src/Polly/Polly.csproj
  src/Polly/RateLimit/LockFreeTokenBucketRateLimiter.cs
  src/Polly/RateLimit/RateLimitRejectedException.cs
  src/Polly/Registry/IConcurrentPolicyRegistry.cs
  src/Polly/Registry/IPolicyRegistry.cs
  src/Polly/Registry/IReadOnlyPolicyRegistry.cs
  src/Polly/Registry/PolicyRegistry.cs
  src/Polly/Timeout/TimeoutEngine.cs
  src/Polly/Utilities/TimedLock.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  test/Polly.Specs/Polly.Specs.csproj
Labels: enhancement, CI/build

#1939 Fix SA1111/SA1513/SA1121/SA1110
  src/Polly/AsyncPolicy.GenericImplementation.cs
  src/Polly/AsyncPolicy.NonGenericImplementation.cs
  src/Polly/Bulkhead/AsyncBulkheadEngine.cs
  src/Polly/Bulkhead/AsyncBulkheadSyntax.cs
  src/Polly/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly/Bulkhead/BulkheadSyntax.cs
  src/Polly/Bulkhead/BulkheadTResultSyntax.cs
  src/Polly/Caching/AsyncCacheEngine.cs
  src/Polly/Caching/AsyncSerializingCacheProvider.cs
  src/Polly/Caching/CacheEngine.cs
  src/Polly/CircuitBreaker/AdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AdvancedCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/AdvancedCircuitController.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerEngine.cs
  src/Polly/CircuitBreaker/CircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/CircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/CircuitStateController.cs
  src/Polly/CircuitBreaker/ConsecutiveCountCircuitController.cs
  src/Polly/CircuitBreaker/SingleHealthMetrics.cs
  src/Polly/Fallback/AsyncFallbackPolicy.cs
  src/Polly/Fallback/AsyncFallbackSyntax.cs
  src/Polly/Fallback/FallbackPolicy.cs
  src/Polly/Policy.SyncGenericImplementation.cs
  src/Polly/Polly.csproj
  src/Polly/RateLimit/AsyncRateLimitEngine.cs
  src/Polly/RateLimit/RateLimitEngine.cs
  src/Polly/Retry/AsyncRetryEngine.cs
  src/Polly/Retry/AsyncRetryPolicy.cs
  src/Polly/Retry/AsyncRetrySyntax.cs
  src/Polly/Retry/AsyncRetryTResultSyntax.cs
  src/Polly/Retry/RetryEngine.cs
  src/Polly/Retry/RetryPolicy.cs
  src/Polly/Retry/RetrySyntax.cs
  src/Polly/Retry/RetryTResultSyntax.cs
  src/Polly/Timeout/AsyncTimeoutPolicy.cs
  src/Polly/Timeout/AsyncTimeoutSyntax.cs
  src/Polly/Timeout/AsyncTimeoutTResultSyntax.cs
  src/Polly/Utilities/TimedLock.cs
  src/Polly/Wrap/AsyncPolicyWrap.cs
  src/Polly/Wrap/AsyncPolicyWrapSyntax.cs
  src/Polly/Wrap/PolicyWrap.cs
  src/Polly/Wrap/PolicyWrapSyntax.cs
Labels: enhancement, CI/build
