Repository App-vNext/Polly, pull requests merged in 2024-10, with the labels that each got.

#2323 Update signing workflow
  .github/workflows/build.yml
Labels: enhancement, dependencies, .NET, github_actions

#2328 Fix S2184, S2104 in Polly.Spec
  test/Polly.Specs/Bulkhead/BulkheadSpecsBase.cs
  test/Polly.Specs/Polly.Specs.csproj
  test/Polly.Specs/Retry/WaitAndRetryAsyncSpecs.cs
  test/Polly.Specs/Retry/WaitAndRetrySpecs.cs
Labels: CI/build

#2331 Seperate mutation tests
  .github/workflows/build.yml
  .github/workflows/mutation-tests.yml
  build.cake
  build.ps1
Labels: enhancement, CI/build

#2344 Add chained rate limiter example
  docs/strategies/rate-limiter.md
  src/Snippets/Docs/RateLimiter.cs
Labels: enhancement, documentation

#2254 Use [DebuggerDisableUserUnhandledExceptions]
  src/Polly.Core/Hedging/Controller/TaskExecution.cs
  src/Polly.Core/Outcome.TResult.cs
  src/Polly.Core/Polly.Core.csproj
  src/Polly.Core/ResilienceContext.cs
  src/Polly.Core/ResiliencePipeline.Async.cs
  src/Polly.Core/ResiliencePipeline.AsyncT.cs
  src/Polly.Core/ResiliencePipeline.Sync.cs
  src/Polly.Core/ResiliencePipeline.SyncT.cs
  src/Polly.Core/Retry/RetryHelper.cs
  src/Polly.Core/Retry/RetryResilienceStrategy.cs
  src/Polly.Core/Utils/StrategyHelper.cs
  src/Polly.Core/Utils/TaskHelper.cs
  src/Polly/Caching/AsyncCacheEngine.cs
  src/Polly/Caching/CacheEngine.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerEngine.cs
  src/Polly/CircuitBreaker/CircuitBreakerEngine.cs
  src/Polly/Fallback/AsyncFallbackEngine.cs
  src/Polly/Fallback/FallbackEngine.cs
  src/Polly/Polly.csproj
  src/Polly/Retry/AsyncRetryEngine.cs
  src/Polly/Retry/RetryEngine.cs
  src/Polly/Timeout/AsyncTimeoutEngine.cs
  src/Polly/Timeout/TimeoutEngine.cs
  src/Shared/DebuggerDisableUserUnhandledExceptionsAttribute.cs
Labels: enhancement

#2355 Document TelemetrySource property of the ExecutionRejectedException
  docs/strategies/circuit-breaker.md
  docs/strategies/rate-limiter.md
  docs/strategies/timeout.md
  src/Snippets/Docs/CircuitBreaker.cs
  src/Snippets/Docs/RateLimiter.cs
  src/Snippets/Docs/Timeout.cs
Labels: documentation
