Repository App-vNext/Polly, pull requests merged in 2024-03, with the labels that each got.

#2004 Update samples to .NET 8
  docs/strategies/retry.md
  samples/DependencyInjection/DependencyInjection.csproj
  samples/GenericPipelines/GenericPipelines.csproj
  samples/Intro/Intro.csproj
  samples/Retries/Retries.csproj
  src/Snippets/Docs/Retry.cs
  src/Snippets/Snippets.csproj
  test/Polly.Specs/Retry/WaitAndRetryForeverAsyncSpecs.cs
Labels: enhancement, documentation, CI/build

#2005 [Docs] Fix calculation of exponential delay in flow chart
  docs/strategies/retry.md
Labels: documentation, bug fix

#2006 Use collection expressions in Cake script
  build.cake
Labels: enhancement, CI/build

#2007 Xml comments cleanup and improvement
  src/Polly.Core/ResiliencePipelineBuilderExtensions.cs
  src/Polly/AsyncPolicy.ExecuteOverloads.cs
  src/Polly/AsyncPolicy.TResult.ExecuteOverloads.cs
  src/Polly/AsyncPolicy.TResult.cs
  src/Polly/AsyncPolicy.cs
  src/Polly/Bulkhead/AsyncBulkheadSyntax.cs
  src/Polly/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly/Bulkhead/BulkheadSyntax.cs
  src/Polly/Bulkhead/BulkheadTResultSyntax.cs
  src/Polly/Caching/AsyncCacheSyntax.cs
  src/Polly/Caching/AsyncCacheTResultSyntax.cs
  src/Polly/Caching/AsyncSerializingCacheProvider.cs
  src/Polly/Caching/CacheSyntax.cs
  src/Polly/Caching/CacheTResultSyntax.cs
  src/Polly/Caching/SerializingCacheProvider.cs
  src/Polly/CircuitBreaker/AdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AdvancedCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncAdvancedCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerTResultSyntax.cs
  src/Polly/DelegateResult.cs
  src/Polly/Fallback/AsyncFallbackSyntax.cs
  src/Polly/Fallback/FallbackSyntax.cs
  src/Polly/IAsyncPolicy.Extensions.cs
  src/Polly/IAsyncPolicy.TResult.cs
  src/Polly/IAsyncPolicy.cs
  src/Polly/ISyncPolicy.Extensions.cs
  src/Polly/ISyncPolicy.TResult.cs
  src/Polly/ISyncPolicy.cs
  src/Polly/IsPolicy.cs
  src/Polly/Policy.ExecuteOverloads.cs
  src/Polly/Policy.HandleSyntax.cs
  src/Polly/Policy.TResult.ExecuteOverloads.cs
  src/Polly/Policy.TResult.cs
  src/Polly/Policy.cs
  src/Polly/PolicyResult.cs
  src/Polly/Registry/IConcurrentPolicyRegistry.cs
  src/Polly/Registry/IPolicyRegistry.cs
  src/Polly/Registry/IReadOnlyPolicyRegistry.cs
  src/Polly/Registry/PolicyRegistry.cs
  src/Polly/Retry/AsyncRetrySyntax.cs
  src/Polly/Retry/AsyncRetryTResultSyntax.cs
  src/Polly/Retry/RetrySyntax.cs
  src/Polly/Retry/RetryTResultSyntax.cs
  src/Polly/Timeout/AsyncTimeoutSyntax.cs
  src/Polly/Timeout/AsyncTimeoutTResultSyntax.cs
  src/Polly/Timeout/TimeoutSyntax.cs
  src/Polly/Timeout/TimeoutTResultSyntax.cs
  src/Polly/Utilities/ExceptionExtensions.cs
  src/Polly/Utilities/SystemClock.cs
Labels: documentation, CI/build

#2008 Xml documentation cleanup
  src/Polly/AsyncPolicy.TResult.cs
  src/Polly/AsyncPolicy.cs
  src/Polly/Bulkhead/AsyncBulkheadTResultSyntax.cs
  src/Polly/Bulkhead/BulkheadPolicy.cs
  src/Polly/Caching/AsyncCacheSyntax.cs
  src/Polly/Caching/AsyncCacheTResultSyntax.cs
  src/Polly/Caching/AsyncSerializingCacheProvider.cs
  src/Polly/Caching/CacheProviderExtensions.cs
  src/Polly/Caching/CacheSyntax.cs
  src/Polly/Caching/CacheTResultSyntax.cs
  src/Polly/Caching/DefaultCacheKeyStrategy.cs
  src/Polly/Caching/ICacheItemSerializer.cs
  src/Polly/Caching/ICacheKeyStrategy.cs
  src/Polly/Caching/NonSlidingTtl.cs
  src/Polly/Caching/ResultTtl.cs
  src/Polly/Caching/SerializingCacheProvider.cs
  src/Polly/Caching/SlidingTtl.cs
  src/Polly/Caching/Ttl.cs
  src/Polly/Caching/TtlStrategyExtensions.cs
  src/Polly/CircuitBreaker/CircuitBreakerSyntax.cs
  src/Polly/CircuitBreaker/CircuitBreakerTResultSyntax.cs
  src/Polly/CircuitBreaker/ICircuitController.cs
  src/Polly/CircuitBreaker/IHealthMetrics.cs
  src/Polly/Context.Dictionary.cs
  src/Polly/DelegateResult.cs
  src/Polly/IsPolicy.cs
  src/Polly/NoOp/NoOpPolicy.cs
  src/Polly/Policy.TResult.cs
  src/Polly/Policy.cs
  src/Polly/PolicyBase.ContextAndKeys.cs
  src/Polly/PolicyBase.cs
  src/Polly/PolicyBuilder.cs
  src/Polly/Polly.csproj
  src/Polly/RateLimit/AsyncRateLimitTResultSyntax.cs
  src/Polly/RateLimit/IRateLimiter.cs
  src/Polly/RateLimit/RateLimitTResultSyntax.cs
  src/Polly/Registry/IConcurrentPolicyRegistry.cs
  src/Polly/Registry/PolicyRegistry.cs
  src/Polly/Retry/AsyncRetrySyntax.cs
  src/Polly/Retry/AsyncRetryTResultSyntax.cs
  src/Polly/Utilities/SystemClock.cs
  src/Polly/Wrap/AsyncPolicyWrap.ContextAndKeys.cs
  src/Polly/Wrap/AsyncPolicyWrap.cs
  src/Polly/Wrap/IPolicyWrap.cs
  src/Polly/Wrap/PolicyWrap.ContextAndKeys.cs
  src/Polly/Wrap/PolicyWrap.cs
Labels: documentation, CI/build

#1984 [Docs] Add cheat sheet for outcome chaos strategy
  docs/community/cheat-sheets.md
  docs/media/cheat-sheet-outcome.pdf
  docs/media/cheat-sheet-outcome.pptx
Labels: documentation

#1994 Document outcome strategy anti-patterns
  docs/chaos/outcome.md
  src/Snippets/Docs/Chaos.Outcome.cs
Labels: documentation

#2030 [Docs] Add cheat sheet for latency chaos
  docs/community/cheat-sheets.md
  docs/media/cheat-sheet-latency.pdf
  docs/media/cheat-sheet-latency.pptx
Labels: documentation

#2031 [Docs] Add cheat sheet for behavior chaos
  docs/community/cheat-sheets.md
  docs/media/cheat-sheet-behavior.pdf
  docs/media/cheat-sheet-behavior.pptx
Labels: documentation

#2033 Remove DiagnosticSource reference from Extensions for NET 6.0 and later
  src/Polly.Extensions/Polly.Extensions.csproj
Labels: CI/build, dependencies
