Repository App-vNext/Polly, pull requests merged in 2024-02, with the labels that each got.

#1947 Fix CA2000/stalled suppressions
  bench/Polly.Core.Benchmarks/Utils/Helper.RateLimiting.cs
  bench/Polly.Core.Benchmarks/Utils/Helper.Timeout.cs
  src/Polly.Core/CircuitBreaker/CircuitBreakerResiliencePipelineBuilderExtensions.cs
  src/Polly.Core/Registry/ResiliencePipelineProvider.cs
  test/Polly.Core.Tests/Utils/Pipeline/CompositePipelineComponentTests.cs
  test/Polly.Specs/Caching/CacheAsyncSpecs.cs
  test/Polly.Specs/Caching/CacheSpecs.cs
  test/Polly.Specs/Caching/CacheTResultAsyncSpecs.cs
  test/Polly.Specs/Caching/CacheTResultSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerTResultAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerTResultSpecs.cs
  test/Polly.Specs/Fallback/FallbackAsyncSpecs.cs
  test/Polly.Specs/Fallback/FallbackSpecs.cs
  test/Polly.Specs/Fallback/FallbackTResultAsyncSpecs.cs
  test/Polly.Specs/Fallback/FallbackTResultSpecs.cs
  test/Polly.Specs/Helpers/PolicyExtensions.cs
  test/Polly.Specs/Helpers/PolicyExtensionsAsync.cs
  test/Polly.Specs/Polly.Specs.csproj
  test/Polly.Specs/RateLimit/RateLimitPolicySpecsBase.cs
  test/Polly.Specs/RateLimit/TokenBucketRateLimiterTestsBase.cs
  test/Polly.Specs/Retry/RetryAsyncSpecs.cs
  test/Polly.Specs/Retry/RetryForeverAsyncSpecs.cs
  test/Polly.Specs/Retry/RetrySpecs.cs
  test/Polly.Specs/Retry/RetryTResultSpecs.cs
  test/Polly.Specs/Retry/RetryTResultSpecsAsync.cs
  test/Polly.Specs/Retry/WaitAndRetryAsyncSpecs.cs
  test/Polly.Specs/Retry/WaitAndRetryForeverAsyncSpecs.cs
  test/Polly.Specs/Retry/WaitAndRetrySpecs.cs
Labels: enhancement, CI/build

#1952 Fix S4056
  test/Polly.Specs/Helpers/Bulkhead/AnnotatedOutputHelper.cs
  test/Polly.Specs/Polly.Specs.csproj
Labels: CI/build

#1951 [Docs] Simmy major differences section
  docs/chaos/index.md
Labels: documentation

#1953 Use var
  test/Polly.Specs/Caching/CacheAsyncSpecs.cs
  test/Polly.Specs/Caching/CacheSpecs.cs
  test/Polly.Specs/Caching/CacheTResultAsyncSpecs.cs
  test/Polly.Specs/Caching/CacheTResultSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerTResultAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerTResultSpecs.cs
  test/Polly.Specs/NoOp/NoOpAsyncSpecs.cs
  test/Polly.Specs/NoOp/NoOpSpecs.cs
  test/Polly.Specs/NoOp/NoOpTResultAsyncSpecs.cs
  test/Polly.Specs/NoOp/NoOpTResultSpecs.cs
  test/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
  test/Polly.Specs/Timeout/TimeoutSpecs.cs
  test/Polly.Specs/Timeout/TimeoutTResultAsyncSpecs.cs
  test/Polly.Specs/Timeout/TimeoutTResultSpecs.cs
Labels: CI/build, code styling clean-ups

#1955 Update NuGet packages
  Directory.Packages.props
Labels: dependencies, .NET

#1963 Fix CA1806
  test/Polly.Specs/Caching/AbsoluteTtlSpecs.cs
  test/Polly.Specs/Caching/RelativeTtlSpecs.cs
  test/Polly.Specs/Caching/ResultTtlSpecs.cs
  test/Polly.Specs/Caching/SerializingCacheProviderAsyncSpecs.cs
  test/Polly.Specs/Caching/SerializingCacheProviderSpecs.cs
  test/Polly.Specs/Caching/SlidingTtlSpecs.cs
  test/Polly.Specs/Polly.Specs.csproj
Labels: CI/build, code styling clean-ups

#1965 Fix S3717
  test/Polly.Specs/Polly.Specs.csproj
  test/Polly.Specs/Timeout/TimeoutAsyncSpecs.cs
  test/Polly.Specs/Timeout/TimeoutSpecs.cs
  test/Polly.Specs/Timeout/TimeoutTResultAsyncSpecs.cs
  test/Polly.Specs/Timeout/TimeoutTResultSpecs.cs
Labels: CI/build, code styling clean-ups

#1966 Add link to chaos engineering blog post
  docs/community/resources.md
  src/Polly.Core/Timeout/TimeoutStrategyOptions.cs
Labels: documentation

#1972 [Docs] Add cheat sheet for fault chaos
  docs/community/cheat-sheets.md
  docs/media/cheat-sheet-fault.pdf
  docs/media/cheat-sheet-fault.pptx
Labels: documentation

#1976 [Docs] Fix antipattern sample code
  docs/strategies/fallback.md
  src/Snippets/Docs/Fallback.cs
Labels: bug, documentation

#1975 [Docs] Improve diagrams for hedging cancellation
  docs/pipelines/index.md
  docs/strategies/hedging.md
  docs/strategies/timeout.md
Labels: documentation

#1977 Add short description to each package
  README.md
Labels: documentation

#1990 Update xunit
  Directory.Packages.props
Labels: dependencies, .NET

#1992 Update NuGet tools
  build.cake
Labels: dependencies, .NET

#1993 Move simmy from unshipped to shipped
  src/Polly.Core/PublicAPI.Shipped.txt
  src/Polly.Core/PublicAPI.Unshipped.txt
Labels: CI/build

#1991 Fix issue #1979: an unhandled exception in half open state must transition to closed and not prevent leaving half open state forever
  src/Polly.Core/CircuitBreaker/CircuitBreakerResilienceStrategy.cs
  src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs
  test/Polly.Core.Tests/CircuitBreaker/CircuitBreakerResilienceStrategyTests.cs
  test/Polly.Core.Tests/CircuitBreaker/Controller/CircuitStateControllerTests.cs
  test/Polly.Core.Tests/Utils/StrategyHelperTests.cs
Labels: bug fix
