Repository App-vNext/Polly, pull requests merged in 2024-05, with the labels that each got.

#2089 Fix CA1000/S4023/S3442/S107/SA1402/SA1649 warnings
  .editorconfig
  Polly.sln
  eng/analyzers/SonarLint.xml
  src/Polly/AsyncPolicy.TResult.cs
  src/Polly/AsyncPolicy.cs
  src/Polly/IAsyncPolicyExtensions.cs
  src/Polly/ISyncPolicyExtensions.cs
  src/Polly/Policy.TResult.cs
  src/Polly/Policy.cs
  src/Polly/PolicyBase.cs
  src/Polly/Polly.csproj
  src/Polly/Wrap/IAsyncPolicyPolicyWrapExtensions.cs
  src/Polly/Wrap/ISyncPolicyPolicyWrapExtensions.cs
Labels: CI/build

#2091 Fix SA1615/SA1623 warnings
  src/Polly/AsyncPolicy.ContextAndKeys.cs
  src/Polly/AsyncPolicy.ExecuteOverloads.cs
  src/Polly/Context.cs
  src/Polly/DelegateResult.cs
  src/Polly/IAsyncPolicy.TResult.cs
  src/Polly/IAsyncPolicy.cs
  src/Polly/ISyncPolicy.TResult.cs
  src/Polly/ISyncPolicy.cs
  src/Polly/IsPolicy.cs
  src/Polly/Policy.ContextAndKeys.cs
  src/Polly/PolicyBase.ContextAndKeys.cs
  src/Polly/PolicyBase.cs
  src/Polly/PolicyBuilder.cs
  src/Polly/PolicyResult.cs
  src/Polly/Polly.csproj
  src/Polly/RateLimit/IRateLimiter.cs
  src/Polly/RateLimit/RateLimitRejectedException.cs
  src/Polly/Registry/IReadOnlyPolicyRegistry.cs
  src/Polly/Registry/PolicyRegistry.cs
  src/Polly/ResultPredicates.cs
  src/Polly/Wrap/AsyncPolicyWrap.cs
  src/Polly/Wrap/IPolicyWrap.cs
  src/Polly/Wrap/PolicyWrap.cs
Labels: CI/build

#2072 Allow changing the severity of resilience events
  docs/advanced/telemetry.md
  src/Polly.Extensions/PublicAPI.Unshipped.txt
  src/Polly.Extensions/Telemetry/SeverityProviderArguments.cs
  src/Polly.Extensions/Telemetry/TelemetryListenerImpl.cs
  src/Polly.Extensions/Telemetry/TelemetryOptions.cs
  src/Snippets/Docs/Telemetry.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryListenerImplTests.cs
  test/Polly.Extensions.Tests/Telemetry/TelemetryOptionsTests.cs
Labels: enhancement

#2099 Fix typos
  README.md
Labels: documentation

#1982 Nullability fixes for chaos outcome strategy
  src/Polly.Core/PublicAPI.Shipped.txt
  src/Polly.Core/PublicAPI.Unshipped.txt
  src/Polly.Core/Simmy/Outcomes/ChaosOutcomeStrategy.cs
  src/Polly.Core/Simmy/Outcomes/ChaosOutcomeStrategyOptions.cs
Labels: CI/build

#2097 Fix potential github action smells
  .github/workflows/after-release.yml
  .github/workflows/build.yml
  .github/workflows/on-push-do-docs.yml
  .github/workflows/ossf-scorecard.yml
  .github/workflows/stale.yml
Labels: enhancement, CI/build, github_actions

#2107 Bump actionlint to 1.7.0
  .github/workflows/actions-lint.yml
Labels: CI/build, dependencies, github_actions

#2112 Fix IDE1006 warning
  src/Polly/Caching/ContextualTtl.cs
  src/Polly/Caching/NonSlidingTtl.cs
  src/Polly/Caching/RelativeTtl.cs
  src/Polly/Caching/SlidingTtl.cs
  src/Polly/CircuitBreaker/AdvancedCircuitController.cs
  src/Polly/CircuitBreaker/AsyncCircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/CircuitBreakerPolicy.cs
  src/Polly/CircuitBreaker/CircuitStateController.cs
  src/Polly/CircuitBreaker/ConsecutiveCountCircuitController.cs
  src/Polly/Context.Dictionary.cs
  src/Polly/IsPolicy.cs
  src/Polly/PolicyBase.ContextAndKeys.cs
  src/Polly/Polly.csproj
  src/Polly/RateLimit/LockFreeTokenBucketRateLimiter.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/AdvancedCircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerTResultAsyncSpecs.cs
  test/Polly.Specs/CircuitBreaker/CircuitBreakerTResultSpecs.cs
Labels: CI/build

#2136 [Docs] Fix pollydocs menu
  docs/advanced/toc.yml
  docs/advanced/use-with-fsharp-and-visual-basic.md
  docs/chaos/toc.yml
  docs/community/toc.yml
  docs/extensibility/toc.yml
  docs/getting-started.md
  docs/pipelines/toc.yml
  docs/strategies/toc.yml
  docs/toc.yml
Labels: documentation, bug fix

#2137 Issue comment automation
  .config/dotnet-tools.json
  .github/workflows/build.yml
  .github/workflows/nuget-packages-published.yml
  eng/Library.targets
Labels: enhancement, CI/build, dependencies, github_actions

#2138 Fix package validation
  .github/workflows/build.yml
  Directory.Build.props
  build.cake
Labels: CI/build, bug fix
