Repository App-vNext/Polly, pull requests merged in 2025-04, with the labels that each got.

#2527 Fix Retry strategy ShouldHandle in example code
  docs/strategies/retry.md
  src/Snippets/Docs/Retry.cs
Labels: documentation, bug fix

#2575 Tweak docs formatting
  docs/strategies/retry.md
  src/Snippets/Docs/Retry.cs
Labels: enhancement, documentation

#2578 [Docs] Dispose registry which contains rate limiters
  .github/wordlist.txt
  docs/pipelines/resilience-pipeline-registry.md
  src/Snippets/Docs/ResiliencePipelineRegistry.cs
Labels: documentation

#2589 Improve mutation tests performance by ensuring solution file isn't discovered
  build.cake
Labels: CI/build

#2590 Update LICENSE metadata
  LICENSE
  eng/Library.targets
Labels: CI/build

#2587 [DOCS] Add HTTP client integration samples
  .github/wordlist.txt
  Directory.Packages.props
  docs/community/http-client-integrations.md
  docs/community/toc.yml
  src/Snippets/Docs/HttpClientIntegrations.cs
  src/Snippets/Snippets.csproj
Labels: documentation

#2592 Dedupe links
  docs/community/http-client-integrations.md
  src/Snippets/Docs/HttpClientIntegrations.cs
Labels: documentation

#2593 Add test analytics
  .github/workflows/build.yml
  Directory.Packages.props
  build.cake
  eng/Test.targets
Labels: enhancement, CI/build

#2596 Simplify test analytics
  .github/workflows/build.yml
  build.cake
Labels: enhancement, CI/build

#2599 Use tip instead of important
  docs/advanced/resilience-context.md
Labels: documentation

#2601 Emit annotation for packages
  .github/workflows/build.yml
Labels: enhancement, CI/build
