Repository App-vNext/Polly, pull requests merged in 2025-01, with the labels that each got.

#2441 Bump cake tools
  build.cake
Labels: dependencies, .NET

#2395 Parallelise mutation tests
  .github/workflows/build.yml
  .github/workflows/mutation-tests.yml
  build.cake
Labels: enhancement, .NET

#2443 Fix package validation
  .github/workflows/build.yml
Labels: CI/build, bug fix

#2428 Synchronize access to `System.ComponentModel.DataAnnotations.Validator`
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.BridgeBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CircuitBreakerOpenedBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CompositeComponentBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.CreationBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.DelegatingComponentBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.GenericOverheadBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.HedgingBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.MultipleStrategiesBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PipelineBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.PredicateBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RateLimiterBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResiliencePipelineBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.ResiliencePipelineProviderBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.RetryBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TelemetryBenchmark-report-github.md
  bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.TimeoutBenchmark-report-github.md
  src/Polly.Core/Utils/ValidationHelper.cs
  test/Polly.Core.Tests/Utils/ValidationHelperTests.cs
Labels: bug fix

#2445 Fix build badges
  README.md
  package-readme.md
Labels: documentation, bug fix

#2447 Fix Registry vs. Provider Migration doc typo
  docs/migration-v8.md
Labels: documentation, bug fix
